### ISSUE TITLE
plasma theme

### ISSUE THREAD

**Issue by Andreas-Kainz** [PapirusDevelopmentTeam/arc-kde#10]
is this a arc-kde plasma theme, or does it work only with kvantum.

my wish is to make a arc plasma theme with color scheme and so on and than a arc look and feel package. I'd like also to work on it, so that my vision get real.

**Comment by Andreas-Kainz** [comment]
the install script is awesome. is it that difficult to make a look and feel package? I don't know but I'd like to learn how to make a usefull look and feel package which the user can download via GHNS.

**Comment by varlesh** [comment]
kvantum - it's not plasma. See readme:
https://github.com/tsujan/Kvantum/tree/master/Kvantum

Look and Feel  not apply kvantum settings, because it's not support. You need install kvantum engine and theme and apply this manually on kvantummanager

**Comment by Andreas-Kainz** [comment]
Do you know how to make a look and feel package for the store.kde.org?

**Comment by varlesh** [comment]
Look and Feel - this only settings for kde configs and preview image:
https://github.com/PapirusDevelopmentTeam/arc-kde/tree/master/plasma/look-and-feel/com.github.varlesh.arc-dark

**Comment by varlesh** [comment]
For example Arc Dark L&F:
```
[kdeglobals][KDE]
widgetStyle=kvantum

[kdeglobals][General]
ColorScheme=Arc Dark

[kdeglobals][Icons]
Theme=Papirus-Dark

[plasmarc][Theme]
name=Arc-Dark

[kwinrc][org.kde.kdecoration2]
theme=__aurorae__svg__Arc-Dark

[kcminputrc][Mouse]
cursorTheme=breeze_cursors
```

**Comment by varlesh** [comment]
But aurorae decorations not apply... some options not apply from Look an Feel, maybe it's bug KDE

**Comment by varlesh** [comment]
applied settings from home folder ~/.config/
For example:
```
[kdeglobals][KDE]
widgetStyle=kvantum
```
It's file **~/.config/kdeglobals** and sections **KDE** applied style **kvantum**

**Comment by varlesh** [comment]
> Do you know how to make a look and feel package for the store.kde.org?

i think need  pack to archive **folder** where contained file **metadata.desktop**
