### ISSUE TITLE
use this theme in plasma on wayland

### ISSUE THREAD

**Issue by Wangrong23** [PapirusDevelopmentTeam/arc-kde#105]
Clicking the window's close button will crash,Session will restart.

**Comment by SmartFinn** [comment]
Seems that bug related to all Aurorae themes https://www.mail-archive.com/kde-bugs-dist@kde.org/msg241314.html

**Comment by Wangrong23** [comment]
> Seems that bug related to all Aurorae themes https://www.mail-archive.com/kde-bugs-dist@kde.org/msg241314.html

Okay thanks
