### ISSUE TITLE
store.kde.org

### ISSUE THREAD

**Issue by Andreas-Kainz** [PapirusDevelopmentTeam/arc-kde#11]
Hi,

I'd like to upload a L&F package to the kde store. Therefore I would upload everything (color scheme, plasma theme, ...) in the kde store. I'm not sure if it's possible to have a team in the store. can I upload stuff in your name @varlesh or should I upload it with my account? I don't want to upload YOUR stuff under my account.

**Comment by varlesh** [comment]
it's impossible, because L&F contained only settings and preview

**Comment by varlesh** [comment]
need public every component

**Comment by varlesh** [comment]
@DarkknightAK Added to store:

- plasma themes
- colorschemes
- aurorae
- kvantum themes
- l&f settings
- yakuake skin
- vlc skin

**Comment by Andreas-Kainz** [comment]
very cool look awesome. I will check for now the icon theme and the window decoration didn't work for me. will talk to the developer to fix stuff if there is a bug.

thanks a lot @varlesh

**Comment by lucasrunner** [comment]
Just to let you know, you can actually add some of this items (plasma theme,
colorscheme, aurorae) as a dependency to your look and feel package. Take a look at metadata.desktop of this theme https://store.kde.org/p/1167792/  especially "X-KPackage-Dependencies" line
