### ISSUE TITLE
Problems in the latest kde

### ISSUE THREAD

**Issue by stykers** [PapirusDevelopmentTeam/arc-kde#110]
For some reason kde updated the theme engine and now panel shadow is broken, other themes appear to have the same issue but the official breeze-dark doesn't.

Anyone got an idea on what caused this?

**Comment by francoism90** [comment]
Screen?

**Comment by Frederick888** [comment]
Wondering whether we've got the same problem... Just upgrade to Plasma 5.16.0 and there's currently an 1px gap between windows and the task bar:
![Screenshot_20190613_235440](https://user-images.githubusercontent.com/4507647/59442555-cd4c7500-8e3d-11e9-9a0d-dd4ad30727ca.png)
![Screenshot_20190614_003425](https://user-images.githubusercontent.com/4507647/59442556-cd4c7500-8e3d-11e9-8ca1-279f93960f95.png)
And yup, breeze doesn't have this issue.

**Comment by stykers** [comment]
> Wondering whether we've got the same problem... Just upgrade to Plasma 5.16.0 and there's currently a 1px gap between windows and the task bar:
> ![Screenshot_20190613_235440](https://user-images.githubusercontent.com/4507647/59442555-cd4c7500-8e3d-11e9-9a0d-dd4ad30727ca.png)
> ![Screenshot_20190614_003425](https://user-images.githubusercontent.com/4507647/59442556-cd4c7500-8e3d-11e9-8ca1-279f93960f95.png)
> And yup, breeze doesn't have this issue.

yep, same problem

**Comment by ArchangeGabriel** [comment]
Also reported (and fixed!) for [materia-kde](https://github.com/PapirusDevelopmentTeam/materia-kde/issues/52). So I guess we could see a fix here soon too, right @varlesh ?

**Comment by stykers** [comment]
> Also reported (and fixed!) for [materia-kde](https://github.com/PapirusDevelopmentTeam/materia-kde/issues/52). So I guess we could see a fix here soon too, right @varlesh ?

last push 8 months ago

**Comment by varlesh** [comment]
I'm temporary not develop Arc now, because not have time for this... On future i'm want redraw some elments, another icons and etc... But not now. Use Materia - it's fresh version with more fixes and updates

**Comment by stykers** [comment]
> I'm temporary not develop Arc now, because not have time for this... On future i'm want redraw some elments, another icons and etc... But not now. Use Materia - it's fresh version with more fixes and updates

can you atleast fix this issue tho? i kinda prefer arc as it is as long as this issue is resolved

**Comment by varlesh** [comment]
fixed

**Comment by kossebau** [comment]
Hi. The one who "broke" the Plasma Theme engine here (actually tried to fix it a bit, see e.g. https://frinring.wordpress.com/2019/04/17/some-theming-fixes-to-arrive-with-plasma-5-16/, but surely might have also regressed other things or at least uncovered hidden issues).

While I just did a first fix Plasma-side to restore old behaviour for Arc, Adwaita & other themes (https://phabricator.kde.org/D21803) there are some open questions how that gap appeared at all.

Someone found that with Arc & Co. the mask elements for the panel-background had an additional 1-pixel margin around them. Which seem to have been removed in the latest commit.

Do you remember why you had added those? They are e.g. not present with Breeze. 

Just trying to collect information for now, before trying to fix some possibly still hidden issue with calculating masks and also reporting them to the window manager for effects.

**Comment by varlesh** [comment]
@kossebau Yes, you right. It's my fault, mask have one pixel unused area and size. I'm delete this one pixel and now all fine.

**Comment by kossebau** [comment]
> @kossebau Yes, you right. It's my fault, mask have one pixel unused area and size. I'm delete this one pixel and now all fine.

Still curious why this pixel had been added once, there surely was a motivation. Any chance you remember why?

**Comment by varlesh** [comment]
@kossebau by my mistake. Didn't see this, because area this one pixel have 100% transparency
