### ISSUE TITLE
Window Decoration is small and misaligned

### ISSUE THREAD

**Issue by hellobbn** [PapirusDevelopmentTeam/arc-kde#113]
I am having trouble with this theme using the latest KDE. The window decoration is small and misaligned. 

Here is my System Info from `kinfocenter`:
**KDE Plasma Version:** 5.16.3
**KDE Frameworks Version:** 5.60.0
**Qt Version:** 5.13.0
**Kernel Version:** 5.2.1-arch1-1-ARCH

The screenshot is in the attachment.

![1](https://user-images.githubusercontent.com/10683168/61469015-0fbf1f80-a9b1-11e9-9534-3a76e3f3f15a.png)

**Comment by enkeyz** [comment]
You need to use the Arc/ArcDark theme, not the ones prefixed with "Kv".

**Comment by hellobbn** [comment]
Thank you for you reply!
