### ISSUE TITLE
Some system dialogs are off

### ISSUE THREAD

**Issue by sryze** [PapirusDevelopmentTeam/arc-kde#115]
In some of KDE system dialogs, for example desktop settings, tray widget settings, this theme doesn't seem to be applied fully because the text color is black and the buttons are white:

![bug](https://user-images.githubusercontent.com/4525736/68539719-f142c100-03b1-11ea-8fc5-029fe3df68e8.png)
![bug2](https://user-images.githubusercontent.com/4525736/68539720-f273ee00-03b1-11ea-84cf-9ba2e0f6f08e.png)
![bug3](https://user-images.githubusercontent.com/4525736/68539721-f43db180-03b1-11ea-9ff3-c16269f97824.png)

**Comment by enkeyz** [comment]
You need to use Kvantum Manager to set the active theme.
![Screenshot_20191130_180146](https://user-images.githubusercontent.com/17646853/69903572-84608c80-139b-11ea-9aa6-665c15277592.png)

**Comment by sryze** [comment]
Thanks
