### ISSUE TITLE
Render lag when using Arc/Arc Dark window decorations

### ISSUE THREAD

**Issue by imtbl** [PapirusDevelopmentTeam/arc-kde#117]
Hello,

I'm encountering a weird issue where the rendering will lag for about 200ms when opening a new window in basically any application (tested with Dolphin, Brave Browser among others) when using Arc/Arc Dark window decorations.
This does not happen when using Breeze window decorations.

It might be compositor-related, because turning the compositor off fixes the issue. I also tried using [kwin-lowlatency](https://github.com/tildearrow/kwin-lowlatency), but that doesn't make any felt difference to me. Aside from that, I've basically tried any workaround/fix I could find on the web when searching for queries like `kwin nvidia compositor lag`.

I'm running KDE Plasma on Arch Linux with the latest proprietary NVIDIA drivers (`440.36`).
Probably relevant hardware:

+ __CPU:__ Intel Core i7-8086K
+ __RAM:__ 32 GB G.SKILL TridentZ DDR4 3200 CL14
+ __GPU:__ ZOTAC GeForce GTX 1080 Ti AMP Extreme
+ __OS Drive:__ Samsung 970 PRO NVMe M.2 1TB

And my X.Org configuration:

```
# nvidia-settings: X configuration file generated by nvidia-settings
# nvidia-settings:  version 440.36

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0" 0 0
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "0"
EndSection

Section "Files"
EndSection

Section "Module"
    Load           "dbe"
    Load           "extmod"
    Load           "type1"
    Load           "freetype"
    Load           "glx"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    # HorizSync source: edid, VertRefresh source: edid
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "LG Electronics 34GK950F"
    HorizSync       225.0 - 225.0
    VertRefresh     48.0 - 144.0
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1080 Ti"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "Stereo" "0"
    Option         "nvidiaXineramaInfoOrder" "DFP-2"
    Option         "metamodes" "DP-0: 3440x1440_144 +0+0 {AllowGSYNCCompatible=On}, DVI-D-0: 1920x1080_60 +3440+450 {AllowGSYNCCompatible=On}"
    Option         "SLI" "Off"
    Option         "MultiGPU" "Off"
    Option         "BaseMosaic" "off"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection
```

**Comment by Odzinic** [comment]
I'm experiencing this same issue with almost the exact same setup except newer Plasma and nvidia driver versions.

**Comment by varlesh** [comment]
i'm clear code on aurorae themes, maybe it's solved render lag

**Comment by varlesh** [comment]
I can only recommend some actions for better performance.
1. Disable effects **Translucency** & **Blur**
2. Set **Rendering engine** to **OpenGL 3.1**
3. Set **Rendering delay** to **Force the smoothest animation**
3. Set **Scaling method** to **With anti-aliasing**

Also change open/close window effect  from **Scale** to **Fade**
