### ISSUE TITLE
[Aurorae] close button and maximized window

### ISSUE THREAD

**Issue by abouvier** [PapirusDevelopmentTeam/arc-kde#12]
A click on the upper right pixel of the screen doesn't close a maximized window when using the Aurorae Arc theme. There is a 1 or 2 px difference between the close button and the edge. Maybe because the window corners are rounded and not rectangular. Anyway, it's very annoying :p

**Comment by varlesh** [comment]
> Anyway, it's very annoying

You can use breeze window decoration if you very annoying with Arc KDE or fix that - sources available!
Also arc-kde aurorae themes have only one pixel for decoration - it's very tiny!

**Comment by abouvier** [comment]
I don't know how to fix that :p
But is it an unexpected behavior, or is it done on purpose?

**Comment by abouvier** [comment]
Ah! The culprit is the property ButtonMarginTop in [Arcrc](https://github.com/PapirusDevelopmentTeam/arc-kde/blob/master/aurorae/themes/Arc/Arcrc#L25). Changing the value from 2 to 0 solve the problem.

**Comment by SmartFinn** [comment]
@abouvier can't add it to upstream, because it looks ugly on a maximized window.

You can fix it manually:

```
sed -i.orig -e 's/ButtonMarginTop=[0-9]\+/ButtonMarginTop=0/' \
    -e 's/TitleEdgeTop=[0-9]\+/TitleEdgeTop=5/' \
    /usr/share/aurorae/themes/Arc*/Arc*rc
```

**Comment by ArchangeGabriel** [comment]
@SmartFinn Something I don’t understand: in Breeze for instance, the button is not glued to the side or top, but clicking on the top right corner works. What makes arc so special here that being able to click this button by going in the top right corner requires a visual change? Can’t it work with the actual aspect?

**Comment by abouvier** [comment]
@ArchangeGabriel I think the button in Breeze is actually maximized to the height of the tittle bar, but that the padding is in the button image itself.

**Comment by ArchangeGabriel** [comment]
That does totally make sense. @SmartFinn Do you think this can be done here too?

**Comment by SmartFinn** [comment]
Guys, Breeze ≠ Aurorae. I tried a lot of combination to make it work on Aurorae, but I had no success.

**Comment by DoS007** [comment]
I'm using Kubuntu 18.04.1 and have the same problem.
I installed the arc dark theme by system settings and chose arc dark decoration in the decoration menu of system settings. But I have the problem this topic is about.

> sed -i.orig -e 's/ButtonMarginTop=[0-9]\+/ButtonMarginTop=0/' \
    -e 's/TitleEdgeTop=[0-9]\+/TitleEdgeTop=5/' \
    /usr/share/aurorae/themes/Arc*/Arc*rc

This does not work for me. I have no such directory. 

> find / -iname 'arc*rc' 2>/dev/null
> /home/dos/.local/share/aurorae/themes/Arc/Arcrc
> /home/dos/.local/share/aurorae/themes/Arc-Dark/Arc-Darkrc

 (no other results).

So I changed in both files TitleEdgeTop=5 and ButtonMarginTop=0. The problem still remains.

?!

**Comment by janhartman** [comment]
@DoS007 Have you managed to fix the problem somehow? I have the same issue, changing the *rc files does not do anything.

**Comment by DoS007** [comment]
@janhartman I think, I didn't fix it. But I'm now back to windows. Scaling with 4k monitor is very inferior in linux plattform. I hope wayland and better nvidia driver will fix that in the future.
