### ISSUE TITLE
arc-kde package for focal

### ISSUE THREAD

**Issue by WMP** [PapirusDevelopmentTeam/arc-kde#120]
Hello, could you build package for ubuntu 20.04 focal?

**Comment by SmartFinn** [comment]
Sorry, I forget to request to build the package on Launchpad. It will be fixed in minutes.

**Comment by SmartFinn** [comment]
The package will be published on [ppa:papirus/papirus](https://launchpad.net/~papirus/+archive/ubuntu/papirus) in 10 minutes.
