### ISSUE TITLE
Incorrect border thickness

### ISSUE THREAD

**Issue by gudvinr** [PapirusDevelopmentTeam/arc-kde#126]
Borders with Arc theme have thickness despite "No borders" setting set.  
Besides unwanted borders it also makes header buttons misaligned and asymmetrical.

That's how breeze theme looks like:
<img width="95" src="https://user-images.githubusercontent.com/1712806/106440756-3f962100-648a-11eb-9717-ed351e937e7f.png">

And that's Arc:
<img width="95" src="https://user-images.githubusercontent.com/1712806/106440765-415fe480-648a-11eb-8bcf-15c7ef2ba0d2.png">

**Comment by varlesh** [comment]
No borders
![image](https://user-images.githubusercontent.com/8083855/145785201-0e4d666c-d22a-44bf-89c5-33596ccb3770.png)
Tiny borders
![image](https://user-images.githubusercontent.com/8083855/145785291-3d6d809c-1f89-4ae5-b2c2-95b23f748560.png)
From theme
![image](https://user-images.githubusercontent.com/8083855/145785353-fd61f822-345c-4f9a-a4ca-e4ecfa836f8c.png)
KDE 5.23.4
