### ISSUE TITLE
Support for Ubuntu 21.10

### ISSUE THREAD

**Issue by AaronTechnic** [PapirusDevelopmentTeam/arc-kde#129]
Arc KDE does not support Ubuntu 21.10, however it supports 21.04. When will we expect 21.10 support? Is it safe to use the 21.04 deb packages?

**Comment by SmartFinn** [comment]
Sorry, forgot copy arc-kde package from [`ppa:papirus/papirus-dev`](https://launchpad.net/~papirus/+archive/ubuntu/papirus-dev) to [`ppa:papirus/papirus`](https://launchpad.net/~papirus/+archive/ubuntu/papirus). Should be fixed within 10 minutes.

**Comment by AaronTechnic** [comment]
Thanks for adding support :)
