### ISSUE TITLE
Release version naming.

### ISSUE THREAD

**Issue by KottV** [PapirusDevelopmentTeam/arc-kde#13]
Приветствую.
В наименовании версии есть тире: 2017.01.10-r46, что изрядно портит процесс опакечивания в deb и rpm. Тире нельзя использовать непосредственно в версии, оно юзается для отделения номера билда в rpm или архитектуры в deb.
Поэтому, приходится в ручную переименовывать версию, что тоже не очень.
Можно это исправить? Как варианты - тильда: ~ или забой: _

**Comment by varlesh** [comment]
Надо у Сергея спросить, я думаю что можно поставить тильду:
```
$(eval VERSION := $(DATE)~r$(COUNT))
```
@SmartFinn 

@KottV Константин, а вы реп хотите сделать?

**Comment by KottV** [comment]
Да, для сюзи.
Пока что поменял на тильду.

**Comment by KottV** [comment]
Кароч:)
В манах к рпм пишут, что тильда для пре-релизов, то есть 2017.01.10~r46 <2017.01.10
Так что, тут хотелось бы знать, это ревизия или пре-релиз) Если ревизия, то я б вообще точку поставил

**Comment by varlesh** [comment]
Может вообще лучше убрать эти все знаки, а оставить только r. Типа такого 2017.01.10r46.
Я в скрипты не лезу :) @SmartFinn  придет, решит тогда как лучше

**Comment by KottV** [comment]
Хз. Пакет в дистре можно вообще называть: "опорный релиз+гиткоммит". Подумайте, я пока что не билдю.

**Comment by SmartFinn** [comment]
Приветствую!

Дайте как-то к консенсусу придем, а то в [PPA](https://launchpad.net/~papirus/+archive/ubuntu/papirus) уже третья форма используется `{revdate}-r{revno}+pkg{revno:packaging}` и тильда уже для другого используется.

Можно `YYYYMMDD.#REV` или  `YYYYMMDD.r#REV` сделать, почти как у [arc-theme](https://github.com/horst3180/arc-theme/releases), но с номером ревизии, которая нужна для возможности сделать несколько релизов в день, хеш коммита в данном примере слишком непредсказуем.

**Comment by SmartFinn** [comment]
В Fedora смотрю такой вариант популярен `YYYYMMDD-REV.gitHASH`.

**Comment by KottV** [comment]
>>В Fedora смотрю такой вариант популярен YYYYMMDD-REV.gitHASH.

я думаю, -REV.gitHASH их билдсервис добавляет
в OBS тоже можно нумерацию пакета крутить как угодно, весь затык в тире в upstream версии
если релизы будут чаще чем раз в день (именно релизы), то имхо действительно лучше YYYYMMDD.REV

**Comment by SmartFinn** [comment]
Посмотрел вокруг и решил просто на `YYYYMMDD` поменять, в худшем случае тег можно откатить и на другой коммит перемапить.

**Comment by KottV** [comment]
Отлично.
Опакетил для сюзи https://software.opensuse.org/search?p=1&baseproject=openSUSE:Tumbleweed&q=arc-kde
