### ISSUE TITLE
Render lag e832dae

### ISSUE THREAD

**Issue by principis** [PapirusDevelopmentTeam/arc-kde#131]
Hi, I just updated to the latest commit e832dae. Even when using the breeze borders, There is by default a massive amount of render lag. This didn't happen with the 20180614 release. (That release did have lag when using Arc border though)

Changing some kvantum settings fixes it (I'm not sure which does the trick, but I think a combination of them):
Diff:
```
--- Kvantum/ArcDark/ArcDark.kvconfig    2022-01-04 15:48:12.479192542 +0100
+++ /home/arthur/.config/Kvantum/ArcDark#/ArcDark#.kvconfig     2022-01-04 15:51:05.111252998 +0100
@@ -20,9 +20,9 @@
 toolbutton_style=1
 x11drag=menubar_and_primary_toolbar
 double_click=false
-translucent_windows=true
-blurring=true
-popup_blurring=true
+translucent_windows=false
+blurring=false
+popup_blurring=false
 opaque=kaffeine,kmplayer,subtitlecomposer,kdenlive,vlc,smplayer,smplayer2,avidemux,avidemux2_qt4,avidemux3_qt4,avidemux3_qt5,kamoso,QtCreator,VirtualBox,trojita,dragon,digikam,qmplay2
 group_toolbar_buttons=false
 vertical_spin_indicators=false
@@ -431,7 +431,7 @@
 transparent_dolphin_view=false
 blur_konsole=true
 transparent_ktitle_label=true
-transparent_menutitle=true
+transparent_menutitle=false
 respect_darkness=true
 kcapacitybar_as_progressbar=true
 force_size_grip=false
@@ -442,9 +442,9 @@
 normal_default_pushbutton=true
 single_top_toolbar=false
 tint_on_mouseover=0
-transparent_pcmanfm_sidepane=true
+transparent_pcmanfm_sidepane=false
 transparent_pcmanfm_view=false
-blur_translucent=true
+blur_translucent=false
 centered_forms=false
 kinetic_scrolling=false
 middle_click_scroll=false
```

**System info**
Operating System: Fedora Linux 35
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.15.12-200.fc35.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7,5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Compositor settings:**
Scale method: smooth
Rendering backend: OpenGL 3.1
Latency: Balance of latency and smoothness
vsync: Automatic

PS: Thank you varlesh for still maintaining this theme!

**Comment by varlesh** [comment]
On new version transparency and blur enabled by default (10%). But you can disable it, if needed.

**Comment by varlesh** [comment]
Render lag maybe possible with **Scale** effect animation, i recommend switch to **Fade**.
Also minimize/restore better work with **Magic Lamp**.
And disable **Maximize**.

**Comment by varlesh** [comment]
I think it's not Arc problem. This effects lagged on Breeze engine and decoration too. I'm set very slow animation and now very good seen how this effects leave a one pixel transparent horizontal line band between the decoration and the window:
https://user-images.githubusercontent.com/8083855/148175878-8d6d1428-1e87-43d4-a351-c3d7c05752d1.mp4

**Comment by principis** [comment]
Thanks for looking into it. Maybe it's a good idea to disable it by default? Not sure what people prefer.
