### ISSUE TITLE
Small taskbar icons

### ISSUE THREAD

**Issue by principis** [PapirusDevelopmentTeam/arc-kde#136]
Since the latest release, the taskbar icons for `Arc Dark` are much smaller. It doesn't look like a large difference, but on a small screen they are much harder to read. 
old: ![Screenshot_20220603_111943](https://user-images.githubusercontent.com/16706228/171826909-585b90a9-f3e1-492e-9de7-bc99f99c863c.png)
new: ![Screenshot_20220603_111909](https://user-images.githubusercontent.com/16706228/171826914-9740d91a-ba74-4ad4-b61c-bc1ba87f3567.png)

Would it be possible to change this?

**Comment by varlesh** [comment]
On new version i'm try set single style for tabbar and tasks:
![image](https://user-images.githubusercontent.com/8083855/171831240-6b83e664-9b86-4434-926a-fbd296a1439e.png)
I try fix it if possible... 
Temporary you can use Arc Color (this theme not updated)

**Comment by varlesh** [comment]
Try with new commit, also i'm update tabbar position. Now it's looks:
![image](https://user-images.githubusercontent.com/8083855/171985068-4ea39985-4440-466d-9e00-b5e4844872ae.png)
not forget clear cache:
`rm -rf ~/.cache/plasm*`

**Comment by varlesh** [comment]
It's solved? Please, let me know

**Comment by principis** [comment]
There sadly doesn't seem much difference?

new: ![Screenshot_20220604_155558](https://user-images.githubusercontent.com/16706228/172003996-ee9302fc-cf39-4860-9747-b5455b2398a3.png)
oldd:  ![Screenshot_20220604_155813](https://user-images.githubusercontent.com/16706228/172004003-f4d7c822-b94a-48c8-98fe-7683aec152a7.png)

But I do like the new look! I understand if you aren't able to fix it :slightly_smiling_face:

**Comment by varlesh** [comment]
I'm reduce widget only vertical
Old version not have layers padding on vertical:
![image](https://user-images.githubusercontent.com/8083855/172037781-3d2d8672-7a7f-4935-bf93-6b29963bd0e9.png)
But now it's have paddings, for single style with tabbar:
![image](https://user-images.githubusercontent.com/8083855/172037923-1399d0a8-5b89-4c0e-b528-7ce4c41ee736.png)
Of course I can reduce the horizontal margins, but I think it will look ugly between the icons.
![image](https://user-images.githubusercontent.com/8083855/172038042-0d341088-ce07-47c6-af8f-28d73baf3d91.png)

PS: Arc Color will be updated too on near future

**Comment by principis** [comment]
Ok, thank you!
