### ISSUE TITLE
audio indicators are not visible

### ISSUE THREAD

**Issue by xqqp** [PapirusDevelopmentTeam/arc-kde#137]
The audio volume indicators in the Audio Volume plasmoid are not visible anymore since the update to Plasma 5.25. See screenshots below.

Breeze Dark 
![image](https://user-images.githubusercontent.com/107686855/174293430-a6de66a2-fb62-408c-8d7e-d9975e70d9aa.png)
Arc Color
![image](https://user-images.githubusercontent.com/107686855/174293451-996594fa-3493-4de0-84bf-7acdf767e776.png)

**Comment by varlesh** [comment]
On Arc Color it's ButtonBackground. You can color as you like
![image](https://user-images.githubusercontent.com/8083855/174419947-2b7e97cf-31a5-41da-a47f-ca360dbaf5d6.png)

**Comment by xqqp** [comment]
@varlesh 
I meant the current noise/audio volume indicator bar, not the button. I marked it in the screenshot below.
Arc only shows a solid bar, with not current volume indication. Breeze shows a half transparent bar with a solid indicator bar inside.

![image](https://user-images.githubusercontent.com/107686855/174429097-5e4e1b76-d2e4-4cae-9e45-5e5be4c54017.png)

**Comment by varlesh** [comment]
Sorry, I didn't understand you initially. Breeze version have 50% opacity on `groove-highlight`. But Arc plasma theme draw as GTK-version and not have opacity:
![image](https://user-images.githubusercontent.com/8083855/174429551-de33068b-dabb-4da2-be18-5575164a1833.png)

**Comment by varlesh** [comment]
You can modify slider SVG if needed `groove-highlight-*` ID's, for example:
```
 <path id="groove-highlight-top" d="m 28,7 0,3 3,0 0,-3 -3,0 z" style="fill:currentColor" class="ColorScheme-Highlight;opacity:0.5"/>
 <path id="groove-highlight-topleft" d="m 27,7 c -1.68216,0 -3,1.31784 -3,3 l 3,0 z" style="fill:currentColor" class="ColorScheme-Highlight;opacity:0.5"/>
 <path id="groove-highlight-topright" d="M 35,10 C 35,8.31784 33.68216,7 32,7 l 0,3 z" style="fill:currentColor" class="ColorScheme-Highlight;opacity:0.5"/>
 <path id="groove-highlight-bottom" d="m 28,18 0,-3 3,0 0,3 -3,0 z" style="fill:currentColor" class="ColorScheme-Highlight;opacity:0.5"/>
 <path id="groove-highlight-bottomleft" d="m 27,18 c -1.68216,0 -3,-1.31784 -3,-3 l 3,0 z" style="fill:currentColor" class="ColorScheme-Highlight;opacity:0.5"/>
 <path id="groove-highlight-bottomright" d="m 35,15 c 0,1.68216 -1.31784,3 -3,3 l 0,-3 z" style="fill:currentColor" class="ColorScheme-Highlight;opacity:0.5"/>
 <path id="groove-highlight-center" d="m 28,11 0,3 3,0 0,-3 -3,0 z" style="fill:currentColor" class="ColorScheme-Highlight;opacity:0.5"/>
 <path id="groove-highlight-left" d="m 24,11 0,3 3,0 0,-3 -3,0 z" style="fill:currentColor" class="ColorScheme-Highlight;opacity:0.5"/>
 <path id="groove-highlight-right" d="m 32,11 0,3 3,0 0,-3 -3,0 z" style="fill:currentColor" class="ColorScheme-Highlight;opacity:0.5"/>
```
But i don't like this style, too faded and does not match the GTK version
![image](https://user-images.githubusercontent.com/8083855/174429847-e6a5bf8c-1efc-4923-931f-104eda55e505.png)

**Comment by xqqp** [comment]
I changed the opacity as you said and now it works great. Thank you.
