### ISSUE TITLE
Latest update differences

### ISSUE THREAD

**Issue by Podesta** [PapirusDevelopmentTeam/arc-kde#138]
Thanks a lot for the project guys, not only here but on the whole projects that you guys maintain.

I've seen a few pics from you guys on the latest version, and since it looks a bit different, I would like to confirm whether the bottom pic is the new intended look, or maybe there are some unintended differences because I'm still on 20.04. That being the case, no worries, I got the old deb and update once I migrate to 22.04.

A few differences I noticed:
 - Different icons on the navbar;
 - Different icons on the application launcher;
 - Permanent bar on top of the open apps;
 - Plus sign on bottom to indicate more than one window open;
 - No more shading to indicate windows that are minimized or not;
 - Bigger distance between icons (due to the permanent bar on top?)
 - Smaller padding between the icon and the bar on top;
 - No more bottom bar to indicate window currently on focus;

![arc-kde-old-zoom](https://user-images.githubusercontent.com/11512008/174448178-ac9b3be4-fe08-4382-9a3d-a59ca37e99af.png)
![arc-kde-old](https://user-images.githubusercontent.com/11512008/174447770-573321c3-c670-40b2-864c-a1009a4e8989.png)
![arc-kde-new](https://user-images.githubusercontent.com/11512008/174447773-3f27b6e8-e99a-4f55-ac86-81135877808e.png)

**Comment by varlesh** [comment]
About tasks, this widget was updated for unification with tabs, also on latest release i'm reduce tasks (by vertical) and tabs, see [this](https://github.com/PapirusDevelopmentTeam/arc-kde/issues/136). Fix more errors.
About icons... Your Plasma version old? New KickOff use another style and not good looking with very old icons:
![image](https://user-images.githubusercontent.com/8083855/174462552-2ef3d671-7e40-422f-8706-6f198601d47f.png)

**Comment by varlesh** [comment]
@Podesta @principis I'm try reduce padding on Tasks.
Before:
![image](https://user-images.githubusercontent.com/8083855/174463475-53ebab47-bddf-4acd-b79f-bafec25fb5e9.png)
After:
![image](https://user-images.githubusercontent.com/8083855/174463518-4c274a0d-82c5-4d36-a35c-eac34f5f5113.png)

**Comment by Podesta** [comment]
Ah,thanks a lot!

Yeah, I feared it was the older version, as I'm still on 20.04. I removed the latest version that got updated with the ppa, and manually installed the older [arc-kde_20190629](https://launchpad.net/~papirus/+archive/ubuntu/papirus/+files/arc-kde_20190629-174+pkg8~ubuntu21.04.1_all.deb). Maybe lock into that version for those still on ubuntu 20.04?

The newer version on your screenshot looks really good! Looking forward to get it once I upgrade to version 22.04.

![image](https://user-images.githubusercontent.com/11512008/174465553-032a4f56-f640-445f-bb6d-3bee9439634c.png)

**Comment by varlesh** [comment]
About PPA, 20190629 have more errors... About Plasma, i'm use KDE Neon UE (formally it's Kubuntu but with fresh Plasma)
![image](https://user-images.githubusercontent.com/8083855/174466384-ccd467a8-d822-4245-b44c-76d2a560a3e2.png)
Ok, i close this.
