### ISSUE TITLE
konsole color scheme broken

### ISSUE THREAD

**Issue by flying-sheep** [PapirusDevelopmentTeam/arc-kde#14]
color0 and color7 have almost no contrast in both schemes. here an excerpt from the dark one:

```ini
[Background]
Color=56,60,74

[Color0]
Color=64,69,82

[Color7]
Color=39,44,53
```

also the intense colors are partly ugly neon…

**Comment by varlesh** [comment]
You can fix that and show me screens with mc, htop, dmesg or another? Sorry, i'm now not have KDE

**Comment by flying-sheep** [comment]
is there another ar~~k~~c terminal color scheme (.Xresources or so) that i can use as base?

**Comment by varlesh** [comment]
I don't understand what you mean with ark - it's archive manager and .Xresources?
Used colors from:
```
/usr/share/color-schemes/Arc.colors
/usr/share/color-schemes/ArcDark.colors
```
or:
```
~/.local/share/konsole/Arc.colorscheme
~/.local/share/konsole/ArcDark.colorscheme
```

**Comment by flying-sheep** [comment]
lol sorry, arc obiviously.

and no: i wanted to know where on the internet i can find color schemes for other terminal emulators (such as .Xresources for Xterm or config files for gnome-terminal or so)

**Comment by varlesh** [comment]
this pack for KDE only and this colors used for konsole and yakuake...

**Comment by flying-sheep** [comment]
yes. and because the colors are wrong, i want a non-KDE version of the terminal color scheme (with proper colors) as reference

**Comment by SmartFinn** [comment]
Screenshots with this issue:
![screenshot from 2017-01-17 17-03-09](https://cloud.githubusercontent.com/assets/819186/22025661/004b3b14-dcd7-11e6-842d-be55e88b0aa9.png)
![screenshot from 2017-01-17 17-02-24](https://cloud.githubusercontent.com/assets/819186/22025663/0053ac04-dcd7-11e6-8c7e-5d4462b79178.png)
![screenshot from 2017-01-17 17-03-46](https://cloud.githubusercontent.com/assets/819186/22025662/005110a2-dcd7-11e6-8345-a7ed4b40a165.png)

**Comment by varlesh** [comment]
i'm update colors... but need test it

**Comment by SmartFinn** [comment]
Looks better, but some colors still has low contrast

![screenshot from 2017-02-18 03-14-24](https://cloud.githubusercontent.com/assets/819186/23093723/89956180-f5f3-11e6-9889-2270ddb7936f.png)
![screenshot from 2017-02-18 03-15-17](https://cloud.githubusercontent.com/assets/819186/23093724/8c3953c4-f5f3-11e6-9b4d-0be560cf14ec.png)
![screenshot from 2017-02-18 03-16-55](https://cloud.githubusercontent.com/assets/819186/23093726/8fffc7ae-f5f3-11e6-999e-7f1a96e6c2fb.png)
![screenshot from 2017-02-18 03-17-40](https://cloud.githubusercontent.com/assets/819186/23093727/91cc5462-f5f3-11e6-8d6d-5a34f40224c2.png)

**Comment by varlesh** [comment]
@SmartFinn Сереж что делать с этим темным шрифтом? Я хз как эту схему разукрасить уже...
может его лучше заменить на цвет морской волны?

**Comment by SmartFinn** [comment]
@varlesh я бы сам поправил, но не в цветах запутался, так где дожнен быть синий - там черный (34 и 1;34). По сути нужно только их поправить, и 30m сделать более контрасным.

Для примера:

![screenshot from 2017-02-18 21-02-26](https://cloud.githubusercontent.com/assets/819186/23096036/97ec2a64-f61d-11e6-8867-2b03d8e9f150.png)

**Comment by SmartFinn** [comment]
@varlesh вот этот скрипт https://transfer.sh/EGB5s/color-columns.sh

**Comment by varlesh** [comment]
да скрипт я нашел, в твоём конфиге много цветных сливается

**Comment by varlesh** [comment]
@SmartFinn вот такой если?
![image](https://cloud.githubusercontent.com/assets/8083855/23096463/c00044e4-f614-11e6-8333-288844dc2336.png)

**Comment by SmartFinn** [comment]
@varlesh выглядит хорошо, сделай только 30m светлее, его не просто так придумали, им элементы подсвечитают.

**Comment by SmartFinn** [comment]
@varlesh и 1;30m не должен быть красным, он в LS_COLORS используется для подсветки временных файлов, желательно поменять на один из оттенков темно-серого.

**Comment by varlesh** [comment]
так?
![image](https://cloud.githubusercontent.com/assets/8083855/23096538/da7469f2-f616-11e6-82ed-7e9ea182f84c.png)

**Comment by SmartFinn** [comment]
@varlesh Отлично :+1:

**Comment by varlesh** [comment]
ща залью, глянешь

**Comment by varlesh** [comment]
@SmartFinn белая:
![image](https://cloud.githubusercontent.com/assets/8083855/23096789/d1139e1e-f61b-11e6-858a-a55211f2fc3e.png)

**Comment by SmartFinn** [comment]
@varlesh тестировал в ranger, mc, htop везде выглядтит классно. Разве что в mc имена файлов тусклые, но это на любителя.

![screenshot from 2017-02-18 22-49-37](https://cloud.githubusercontent.com/assets/819186/23096790/ab98e12e-f62c-11e6-9ed8-f78cd7ae153a.png)


В светлой неуверен в cyan цвете, в mc может быть слишком ядовито, выложи - посмотрю.

**Comment by varlesh** [comment]
залил чудок другой

**Comment by varlesh** [comment]
там 30m и 37m практически совпадают
![image](https://cloud.githubusercontent.com/assets/8083855/23096853/59e35454-f61d-11e6-9b8c-c3de0e001445.png)

**Comment by varlesh** [comment]
впринципе все читабельно + mc норм смотрится

**Comment by SmartFinn** [comment]
@varlesh 37 и 1;37 нужно менять на темно-серые немного светлее 0m и 1m, совсем не читаемо:

![screenshot from 2017-02-18 23-03-57](https://cloud.githubusercontent.com/assets/819186/23096877/a895cdd2-f62e-11e6-8e4d-a78e9df9e45b.png)

**Comment by varlesh** [comment]
@SmartFinn Попробуй поправь как считаешь нужным

**Comment by SmartFinn** [comment]
@varlesh проблема улетает если Color 1  сделать темным, плюс mс даже смотрится лучше

![screenshot from 2017-02-18 23-26-45](https://cloud.githubusercontent.com/assets/819186/23097006/fcada888-f631-11e6-94d1-cb71b44d4689.png)

Подбери туда какой-нибудь цвет в средних тонах ближе к темному, а то я здесь не силен.

**Comment by varlesh** [comment]
нет, темный не вариант... ща попробую, че-нибудь сварганить. Черз что сислог смотришь?

**Comment by SmartFinn** [comment]
@varlesh говорю там темный нужен, сам проверь. lnav утилита называется, в ranger, moc и mc тоже смотрится лучше. Color 1 это же темный фоновый цвет в том числе.

**Comment by varlesh** [comment]
этот попробуй
[Arc.colorscheme.txt](https://github.com/PapirusDevelopmentTeam/arc-kde/files/785361/Arc.colorscheme.txt)

**Comment by varlesh** [comment]
![image](https://cloud.githubusercontent.com/assets/8083855/23097101/2ed7e77e-f623-11e6-8ac5-a0a1f66aa035.png)

**Comment by varlesh** [comment]
или наверное лучше еще темней:
![image](https://cloud.githubusercontent.com/assets/8083855/23097115/a82bb416-f623-11e6-90ac-89ae153d7ffa.png)

**Comment by SmartFinn** [comment]
@varlesh ага, 78,78,88 смотрится не плохо.

**Comment by SmartFinn** [comment]
@varlesh как есть оставляй, отлично получилось :+1:

**Comment by varlesh** [comment]
ну наконец-то... ))
