### ISSUE TITLE
arc-kde-git doesn't show up in Application Style -> GTK settings

### ISSUE THREAD

**Issue by mustaqimM** [PapirusDevelopmentTeam/arc-kde#16]
After installing arc-kde-git from the AUR, it doesn't show up, but other theme options are available like Window decorations and in Kvantum but it isn't in the GTK settings.

**Comment by abouvier** [comment]
Because it's not a GTK theme. You should use `arc-gtk-theme` or `gtk-theme-arc-git` for a consistent GTK theme.

**Comment by mustaqimM** [comment]
I see, thanks. I was confused because it now says
> Arc KDE - This is a port of the popular [GTK theme Arc](https://github.com/horst3180/Arc-theme) for Plasma 5 desktop with a few additions and extras  

in the READ.ME
