### ISSUE TITLE
Aurorae themes broken?

### ISSUE THREAD

**Issue by ArchangeGabriel** [PapirusDevelopmentTeam/arc-kde#17]
That’s how they look on my system:

![spectacle t16120](https://cloud.githubusercontent.com/assets/490531/22672997/b2cd1054-ecd7-11e6-9fe6-e0a004945ad7.png)

Is this expected?

**Comment by SmartFinn** [comment]
Can you make a real screenshot instead preview? You don't mention which version of KDE/distro you are using.

**Comment by ArchangeGabriel** [comment]
Yes, sorry. This is ArchLinux, Plasma 5.9.

Not on my computer anymore right now, but it looks even worse than the preview. Will upload one tomorrow.

**Comment by SmartFinn** [comment]
Hmm, can't confirm it


![screenshot from 2017-02-07 13-54-54](https://cloud.githubusercontent.com/assets/819186/22690159/0cad78c4-ed3d-11e6-8c49-7bd6651ccefe.png)

manjaro-kde-17.0-beta1-unstable-x86_64.iso
```
[manjaro@manjaro ~]$ plasmashell --version
plasmashell 5.9.0
```

**Comment by ttv20** [comment]
I have the same problem...
openSUSE
Plasma 5.9.0
RTL system (maybe this is problem?)

**Comment by ttv20** [comment]
Its look wired on some apps:
system settings, dolphin, okular, vlc, kate,
but other kde apps look right:
ark, konsole, kwrite, ksysguard, kdesu, gwenview

I couldn't determine what the rule about this
even kwrite and kate are different - they base on the same source code!

**Comment by ArchangeGabriel** [comment]
So this is how Kate looks like for instance.
![spectacle w20636](https://cloud.githubusercontent.com/assets/490531/22693075/1b61a8f4-ed42-11e6-8bd1-90bf00ebc606.png)

I have an hypothesis: could this be because of HiDPI?

**Comment by SmartFinn** [comment]
Can test with an another Aurorae themes? For example https://store.kde.org/p/1002663/

**Comment by ArchangeGabriel** [comment]
@SmartFinn Exactly the same issue with Freeze.

**Comment by SmartFinn** [comment]
Already exist on KDE bugtracker https://bugs.kde.org/show_bug.cgi?id=375868

**Comment by ArchangeGabriel** [comment]
@SmartFinn Thanks, subscribed.

**Comment by ArchangeGabriel** [comment]
The upstream issue has been fixed. This should be available in some future release. ;)
