### ISSUE TITLE
Arc KDE plasma theme can't be installed via "get new theme" from KDE Store

### ISSUE THREAD

**Issue by lucasrunner** [PapirusDevelopmentTeam/arc-kde#18]
When one tries to install https://store.kde.org/p/1167639/ via "get new theme" in System settings it will silently fail. The reason is that arc-kde-plasma.tar.xz have two themes inside: Arc-Color and Arc-Dark.
They should be packed separately with different entries in KDE Store.

**Comment by SmartFinn** [comment]
It seems that it was fixed long ago.
