### ISSUE TITLE
Please add dependencies to Arc KDE  look and feel theme

### ISSUE THREAD

**Issue by lucasrunner** [PapirusDevelopmentTeam/arc-kde#19]
Since Plasma 5.9 you can specify dependencies in your look and feel theme. It will download all required resources from KDE Store.

Please add:

`X-KPackage-Dependencies=kns://colorschemes.knsrc/api.kde-look.org/1167638,kns://plasma-themes.knsrc/api.kde-look.org/1167639,kns://aurorae.knsrc/api.kde-look.org/1167637,kns://icons.knsrc/api.kde-look.org/1166289`

to your metadata.desktop

It will install:
https://store.kde.org/p/1167638/
kns://colorschemes.knsrc/api.kde-look.org/1167638,
https://store.kde.org/p/1167639/
kns://plasma-themes.knsrc/api.kde-look.org/1167639,
https://store.kde.org/p/1167637/
kns://aurorae.knsrc/api.kde-look.org/1167637,
https://store.kde.org/p/1166289/
kns://icons.knsrc/api.kde-look.org/1166289

More info:
https://community.kde.org/How_to_create_Look_and_Feel_Package

**Comment by varlesh** [comment]
added, soon updated on store-kde... but kvantum engine not possible :(

**Comment by varlesh** [comment]
store-kde archive updated

**Comment by lucasrunner** [comment]
> added, soon updated on store-kde... but kvantum engine not possible :(

As long as an application provide  the AppStream metadata and is available in the main repo you can use AppStream URI scheme to specify it in your metadata.desktop. However I don't know any distribution that have kvantum in the main repository. For example if you will add 
appstream://plank.desktop it should install plank, at least in theory.

**Comment by varlesh** [comment]
@lucasrunner you try it?

**Comment by varlesh** [comment]
i'm try with kns://kvantumthemes.knsrc/api.kde-look.org/1167643 - not worked, because kvantum theme installed on ~/.config/Kvantum but L&F install all on ~/.local/share/

**Comment by lucasrunner** [comment]
No I didn't tried and to my knowledge kvantum themes do not provide knsrc file

**Comment by varlesh** [comment]
Yes maybe it's comfortable - install from plugin browser, but not like me. Mostly tools not availble and not possible. I recommend install pack from GitHub or repos - it's fulled and fine looking :)
Issue closed...
