### ISSUE TITLE
Version with transparency turns some windows fully transparent

### ISSUE THREAD

**Issue by Baemir** [PapirusDevelopmentTeam/arc-kde#20]
![screenshot_20170305_030111](https://cloud.githubusercontent.com/assets/7771304/23584985/4eff5edc-0150-11e7-82db-d3769c619a8e.png)

Somehow I don't think this is intentional, lol.

**Comment by SmartFinn** [comment]
Distro?
Plasma version?
Do you use Kvantum?

Manjaro 16.10.3 with qBittorrent v3.3.7 looks fine.
