### ISSUE TITLE
Incorrect network icon?

### ISSUE THREAD

**Issue by ghost** [PapirusDevelopmentTeam/arc-kde#22]
![screenshot_20170310_163850](https://cloud.githubusercontent.com/assets/24662041/23797958/f2f3f4ce-0567-11e7-9296-70e53906e0f7.png)
When network is disconnected, the tray icon should be white or black?

**Comment by SmartFinn** [comment]
Changed to ![network-wireless-available](https://cloud.githubusercontent.com/assets/819186/23806369/16332ba0-05ca-11e7-90eb-1b415ce3e4bf.png). Please check.

**Comment by ghost** [comment]
Thank you!!!!!!
