### ISSUE TITLE
add arc-darker and borderless versions

### ISSUE THREAD

**Issue by nlgranger** [PapirusDevelopmentTeam/arc-kde#24]
If this is not too difficult, that would be a nice addition.

**Comment by marksev1** [comment]
+1 for arc-darker its my favourite theme by far.

**Comment by varlesh** [comment]
Really, it's impossible. Because on Gnome DE used symbolic icons... We have more trouble on KDE with darker theme.
I try this:
![image](https://user-images.githubusercontent.com/8083855/27405844-2df11494-56e4-11e7-81a6-d1aa97a2b7cf.png)

**Comment by varlesh** [comment]
Theme from previous screen:
[ArcDarkerTransparent.tar.gz](https://github.com/PapirusDevelopmentTeam/arc-kde/files/1092881/ArcDarkerTransparent.tar.gz)
For KDE/Qt used with Papirus-Dark icons for GTK2 used Papirus icons... but it's not good.

**Comment by marksev1** [comment]
Its not so good, but its not so bad either :).

**Comment by himanshub16** [comment]
:+1: for Arc-Darker. It looks prettier on my laptop compared to Arc-Dark.

**Comment by varlesh** [comment]
Soon Arc Darker:
![image](https://user-images.githubusercontent.com/8083855/30229787-5af645a6-94f4-11e7-9c1c-edb3df844ef6.png)
