### ISSUE TITLE
Border really thin, hard to grab

### ISSUE THREAD

**Issue by Eneen** [PapirusDevelopmentTeam/arc-kde#26]
Here is comparison to breeze, take a look:
![peek 2017-03-22 09-44](https://cloud.githubusercontent.com/assets/25537418/24189498/89aee852-0ee5-11e7-9ca6-5d43d5df743d.gif)

**Comment by ArchangeGabriel** [comment]
You know you can change the size in this exact settings windows, right (it’s in the bottom right)?

**Comment by Eneen** [comment]
oh... I can say I'm really blind! But still maybe it's worth to change default value, as setting minimal turns border off.

**Comment by SmartFinn** [comment]
@Eneen No, sorry, I leave it as it is.
