### ISSUE TITLE
Windows title is not centered properly

### ISSUE THREAD

**Issue by yujqiao** [PapirusDevelopmentTeam/arc-kde#27]
Distro: Arch Linux 
DE: KDE 5.32.0 / Plasma 5.9.4
with kvantum
It seems that the title is centered according to the space apart from the windows buttons, which should be centered according to the whole title bar.
<img width="419" alt="screenshot_20170327_133638" src="https://cloud.githubusercontent.com/assets/20105061/24342279/8ed0a4ee-1285-11e7-8d3f-ff6f6d934a2a.png">

**Comment by SmartFinn** [comment]
This can't be fixed. Window title already aligned by the center.

```
$ > grep Alignment Arc-Darkrc
TitleAlignment=Center
TitleVerticalAlignment=Center
```
