### ISSUE TITLE
Menus seem oddly aligned

### ISSUE THREAD

**Issue by FuturePilot** [PapirusDevelopmentTeam/arc-kde#29]
This doesn't seem right. There's way too much of a gap at the top and the left side is not aligned with the top menu highlight. 
![screenshot_20170403_090428](https://cloud.githubusercontent.com/assets/4391536/24610862/30281d68-184e-11e7-9992-4efcbfcefad9.png)

arc-kde 20170401-60+pkg3~ubuntu16.10.1 on Kubuntu 16.10

**Comment by SmartFinn** [comment]
This issue related to Kvantum themes:

- Arc
- ArcDark
- ArcDarkTransparent
- ArcTransparent

Choose one of theme **KvArc** or **KvArcDark** in Kvantum Manager for now.

**Comment by FuturePilot** [comment]
There is still a slight alignment issue with KvArc(Dark) though not as extreme. Note the left side of the menu and the menu item highlight.
![screenshot_20170506_120655](https://cloud.githubusercontent.com/assets/4391536/25775659/4967fb56-3278-11e7-822e-2401ed693b86.png)

**Comment by SmartFinn** [comment]
@FuturePilot KvArc isn't part of Arc-KDE, it's built-in theme in Kvantum.

**Comment by saivert** [comment]
So what is the difference between KvArc and the Kvanum Arc theme that is part of this repo?
What is better? Seems like KvArc is more recently updated.

**Comment by varlesh** [comment]
@FuturePilot It's impossible fixed, because for highlight and pressed used similar colors.
See when you point cursor to menu used gray color:
![image](https://user-images.githubusercontent.com/8083855/27182331-4fd8b144-51ca-11e7-8a82-fb7a5ffccf96.png)
when you press button (menu) used blue color:
![image](https://user-images.githubusercontent.com/8083855/27182358-687e8f02-51ca-11e7-95a6-08277c2b5c8c.png)
```
[MenuBarItem]
inherits=PanelButtonCommand
interior.element=menuitem
frame=false
text.margin.top=3
text.margin.bottom=3
text.margin.left=5
text.margin.right=5
text.press.color=#ffffff
text.focus.color=#ffffff < this line
```

**Comment by varlesh** [comment]
i don't know how use different text color for highlight and pressed item

**Comment by varlesh** [comment]
@FuturePilot i'm try use align with 0px, but this cut shadow for menu:
![image](https://user-images.githubusercontent.com/8083855/27183811-7fff5210-51cf-11e7-9869-47af50fa06e3.png)
This don't like me, restore old version

**Comment by gmsanchez** [comment]
Is this solved? I am having very similar issues using Arc Theme and applet-window-appmenu or global menu. If I click on the menu, at first it is aligned, but if I move the mouse with the menu opened, it start to show odd alignment. Here are some screenshots

![screenshot_20190227_000650](https://user-images.githubusercontent.com/2853668/53464004-87eb6f80-3a27-11e9-8060-385815cac248.png)
![screenshot_20190227_000724](https://user-images.githubusercontent.com/2853668/53464005-87eb6f80-3a27-11e9-9eb0-c874dae34fb3.png)
