### ISSUE TITLE
Margin of context menu.

### ISSUE THREAD

**Issue by ANtlord** [PapirusDevelopmentTeam/arc-kde#31]
Hello! First of all it is great work.

I have encountered margin of context menu. And all context menus has this margin. I do right click by on desktop or dolphin or another non-gtk application. Probably it's not an issue and it can be fixed by editing of  a config from the project. But I don't which config should edited for correcting this margin.

I've attached screenshot for clearance
https://www.dropbox.com/s/vzblctkaa7jaelv/shot2017-04-21T19-36-59.png?dl=0

Thanks. Sorry if my english is not clear.

**Comment by ANtlord** [comment]
Oops. Sorry. It was metioned [there](https://github.com/PapirusDevelopmentTeam/arc-kde/issues/29).

**Comment by SmartFinn** [comment]
Yes, I close this issue. Subscribe to that #29
