### ISSUE TITLE
Deactivated title bar buttons behave incorrectly

### ISSUE THREAD

**Issue by nerdius** [PapirusDevelopmentTeam/arc-kde#32]
The theme lacks icons for deactivated buttons, hence deactivated buttons are displayed like normal ones in active windows, while entirely disappear in inactive ones.

For example, in an active KCalc window, where the _Maximize_ button is deactivated, it shows up as normal:

![KCalc active](https://cloud.githubusercontent.com/assets/2781117/25308374/c62cf9f8-27c3-11e7-9643-6c20a0e7fd6b.png)

However, when the window is inactive, it disappears altogether:

![KCalc inactive](https://cloud.githubusercontent.com/assets/2781117/25308392/32ed2d6a-27c4-11e7-9352-f4040a9620d1.png)

**Comment by SmartFinn** [comment]
This problem is relevant for all Aurorae Themes and can't be fixed for Arc-KDE.

**Comment by SmartFinn** [comment]
Was wrong. It's can be fixed.

**Comment by nerdius** [comment]
Yeah. You can also add one for _deactivated-inactive-center_.

The documentation, of course, is [here](https://techbase.kde.org/User:Mgraesslin/Aurorae).

**Comment by SmartFinn** [comment]
@giogziro95 I think that's enough.

**Comment by giogziro95** [comment]
I just noted what; it wasn't intended to be a request.

**Comment by nerdius** [comment]
I just noted that; it wasn't intended to be a request.
