### ISSUE TITLE
Splash change (sugestion)

### ISSUE THREAD

**Issue by arthurflor23** [PapirusDevelopmentTeam/arc-kde#33]
This isn't a bug, but a sugestion..

The sugestion is change the background from splash initial to a black background.. like this:
![image](https://cloud.githubusercontent.com/assets/11759042/25337597/e0d05aec-28d2-11e7-82d2-15c9b8a6b831.png)

Similar to current KDE splash

**Comment by ArchangeGabriel** [comment]
I’d like that too! Maybe could be made as an option?

**Comment by nerdius** [comment]
Also, KDE logo should be replaced with Plasma logo (similar to [what's used for Kickoff icon by default](https://www.kde.org/announcements/plasma-5.9/plasma-5.9.png)), IMHO.

**Comment by ArchangeGabriel** [comment]
I, for one, prefer KDE icon actually. But that’s a matter of taste. ;)
