### ISSUE TITLE
[Suggestion] could we have an option to have these window controls?

### ISSUE THREAD

**Issue by ghost** [PapirusDevelopmentTeam/arc-kde#34]
Hello, I love everything about this theme besides the window controls. I'd like to have an option to pick [these](https://camo.githubusercontent.com/1a5a22e9b75be646793dd6fbdfb7c357fa6710ac/687474703a2f2f692e696d6775722e636f6d2f7a5543317048542e706e67) instead (just those three buttons, minimize, maximize and close).

It's already here but it doesn't work like this one. https://github.com/andreisergiu98/arc-flatabulous-theme

**Comment by SmartFinn** [comment]
Hi. I don't have a plan to add a theme with those window controls. If someone creates a fork, I'll add a link to it.

**Comment by ghost** [comment]
I would but I don't know how. Could basic knowledge of CSS make this happen? If so could you point me at the .css file that I should be editing?

**Comment by SmartFinn** [comment]
You only need Inkscape skills. [close.svgz](https://github.com/PapirusDevelopmentTeam/arc-kde/tree/master/aurorae/themes/Arc/close.svgz), [maximize.svgz](https://github.com/PapirusDevelopmentTeam/arc-kde/tree/master/aurorae/themes/Arc/maximize.svgz) and [minimize.svgz](https://github.com/PapirusDevelopmentTeam/arc-kde/tree/master/aurorae/themes/Arc/minimize.svgz) files should look like those sources https://github.com/andreisergiu98/arc-flatabulous-theme/tree/master/common/unity/window-buttons

**Comment by ghost** [comment]
Wow that's cool. I'm not bad in Inkscape as well. Thanks.

**Comment by ghost** [comment]
I edited them out but can't seem to find them in the system. Where should I replace mine with the original ones?

**Comment by SmartFinn** [comment]
@skullscream Look in  `~/.local/share/aurorae/themes/`  or `/usr/share/aurorae/themes/`.

**Comment by ghost** [comment]
I replaced my svgz files with the arc dark ones and this is what I get http://i.imgur.com/enLwwft.png

Any idea what it might be?

Here are the three files if you'd like to try for yourself http://www.filedropper.com/buttons_1

Those buttons still work, I'm still able to close, minimize and maximize they are just not visible for some reason.

**Comment by SmartFinn** [comment]
Each button in the svgz file must have ID (`Object` - `Object Properties...` in Inkscape).

IDs:
- active-center
- hover-center
- pressed-center
- inactive-center
- deactivated-center

The documentation https://techbase.kde.org/User:Mgraesslin/Aurorae#Buttons

**Comment by ghost** [comment]
This is a rectangle without a fill/stroke and then circle put into it and grouped together, yes?

**Comment by SmartFinn** [comment]
There no a rectangle, just circle inside the group with ID.

**Comment by ghost** [comment]
I still have no idea what I'm doing wrong.

**Comment by SmartFinn** [comment]
Add your svgz files into zip archive and attach here, I'll look.

**Comment by ghost** [comment]
[files.zip](https://github.com/PapirusDevelopmentTeam/arc-kde/files/979913/files.zip)
Sorry to bother you this much, just never did this before, objects, icons....

**Comment by SmartFinn** [comment]
You changed Label, not an ID
![screenshot from 2017-05-05 21-05-18](https://cloud.githubusercontent.com/assets/819186/25758416/2bcb5bfc-31d7-11e7-90e7-3f2aa37bd0ab.png)

**Comment by ghost** [comment]
Still a nope, unfortunately. http://i.imgur.com/YEbOHZ6.png
Even after I changed all IDs like that for every button.

**Comment by SmartFinn** [comment]
Works on my system [Arc-Dark.tar.gz](https://github.com/PapirusDevelopmentTeam/arc-kde/files/979986/Arc-Dark.tar.gz)
![screenshot from 2017-05-05 21-32-48](https://cloud.githubusercontent.com/assets/819186/25759311/91042780-31da-11e7-933a-9aba9ed93010.png)

**Comment by ghost** [comment]
Had to re-install the theme and icon pack. Now it's working, finally. They still could do some work on my part so hovering and pressing is more obvious. Thank you so much dude.
Should I fork this one and make changes or?

**Comment by SmartFinn** [comment]
As you wish. Ping me if you made a repo with these themes. I'll add a link to it in the [extras](https://github.com/PapirusDevelopmentTeam/arc-kde#extras).

**Comment by ghost** [comment]
Ok. And how do I ping exactly? :D
Is that github's version of PMs?

**Comment by SmartFinn** [comment]
@skullscream create a separate repository that contains only the modified Aurorae themes like this project https://github.com/simoniz0r/kde-gaps

Also, change a name of the repo to `Arc-KDE-Flatabulous-theme` or something like that.

**Comment by danielsanfr** [comment]
@skullscream I already gave you a star. It was very good what you did. I just wondered if the size of the controls should be a little smaller?

**Comment by ghost** [comment]
They are 16x16px which seems pretty good. They take up most of the window which is what I intended. Smaller ones might be harder to hit when rage quitting :D
