### ISSUE TITLE
New version tag

### ISSUE THREAD

**Issue by KottV** [PapirusDevelopmentTeam/arc-kde#35]
Hi. It seems that some new important fixes arrived.
Should we tag new version for packaging? Or lets switch to git-date-rolling, like Papirus?

**Comment by SmartFinn** [comment]
Hi. I made the new release, but I think the switch to rolling release will be preferable.

**Comment by KottV** [comment]
ok!

**Comment by ArchangeGabriel** [comment]
Hum, releases are good for packaging into distributions. I’d like you to continue releasing new version from time to time if that’s OK with you.

**Comment by SmartFinn** [comment]
@ArchangeGabriel I will do. Don't worry :)
