### ISSUE TITLE
Konsole menubar color problem

### ISSUE THREAD

**Issue by ghost** [PapirusDevelopmentTeam/arc-kde#36]
I've been having this weird color issue with the konsole menubar, any tips on how to fix it?
It's on arc transparent btw
![screenshot_20170507_131231](https://cloud.githubusercontent.com/assets/9671865/25778684/317b3e40-3327-11e7-9ff8-4555f4eae67a.png)

**Comment by SreckoM** [comment]
Yup me too, and fix with script does not work as script is not located where suggested.

**Comment by ghost** [comment]
@SreckoM afaik that script is for gtk apps which works btw for gtk apps

**Comment by SreckoM** [comment]
O you are right, sorry missed that.

**Comment by zakisaad** [comment]
That script isnt even working for GTK apps for me

**Comment by varlesh** [comment]
Yes, this script for only GTK2 apps and not support transparent. For right work use kvantum engine for Qt-apps.

**Comment by ghost** [comment]
I am using kvantum

**Comment by varlesh** [comment]
Maybe you use not ArcDarkTransparent theme? Also kvantum have KvArcDark - it's not my theme

**Comment by ghost** [comment]
Yup, using ArcDarkTransparent, first thing I did after changing to kvantum

**Comment by varlesh** [comment]
Hm, it's strange... Maybe konsole use another widget for menubar? 
This bug reproduced on other KDE-aaps (dolphin, kate and etc..) ?

**Comment by ghost** [comment]
Only on konsole on my end, no such issue on kate nor dolphin

**Comment by varlesh** [comment]
@Ornim Sorry, but it's fix impossible. 
See kvantum developer comment:

> This is not a bug.
> 
> Kvantum can make a window translucent only if it isn't already so. Konsole and QTerminal have hard-coded translucency, so, Kvantum doesn't touch their windows. In other words, the translucency of such apps isn't Kvantum's responsibility.
> 
> Another example is LXQt panel, whose possible translucency can be caused only by its stylesheet and if that stylesheet doesn't have transparency, Kvantum can't make the panel translucent.

**Comment by ghost** [comment]
Interesting

**Comment by varlesh** [comment]
Temporary solution - disable menubar (Ctrl+Shift+M)

**Comment by ghost** [comment]
Yeah that's what I've been doing
