### ISSUE TITLE
Using a different icon theme

### ISSUE THREAD

**Issue by bharadwaj-raju** [PapirusDevelopmentTeam/arc-kde#37]
After applying Arc Dark theme from System Settings → Workspace Theme → Look and Feel, the icons changed: In applications, there were no icons (beside buttons, for example).

I preferred the Breeze Dark icons to the ones that come with Arc. So, I changed icon theme back to Breeze Dark in System Settings.

However, Arc is still using whatever custom theme it uses, and Breeze is only applied in the applications.

[SCREENSHOT] In applications, Breeze Dark icons:
![look_and_feel_arcdark_breezeicons](https://cloud.githubusercontent.com/assets/15855081/26387391/e121a118-406a-11e7-9df2-faed4ca93d50.png)

[SCREENSHOT] In menu and panel, Arc's custom theme
![menu_and_panel_arcdark_nobreezeicons](https://cloud.githubusercontent.com/assets/15855081/26387394/ed4bf59c-406a-11e7-96ae-8fc37cca939c.png)

**Comment by bharadwaj-raju** [comment]
Workaround: remove the directories `icons/` and `icontasks/` from `/usr/share/plasma/desktoptheme/Arc-Dark/`.

Arc-Dark should respect user settings and not include custom icons by default, as it stops the user from using their own choice of icons.

**Comment by ArchangeGabriel** [comment]
@bharadwaj-raju Those icons are part of the Desktop Theme. They are two places where icons are set: Icons and Desktop Theme. If that is an issue, it’s with KDE Plasma, not Arc. Any other theme will be the same.

**Comment by varlesh** [comment]
@bharadwaj-raju If you want use Breeze icons on Arc plasma theme you can delete folder **icons** on plasma theme directory.
