### ISSUE TITLE
Wireshark highlighted packet/text white

### ISSUE THREAD

**Issue by enkeyz** [PapirusDevelopmentTeam/arc-kde#38]
Hello guys! 

Just installed Arc theme for my desktop, but if I select a package/or text in Wireshark with Qt(GTK version of Wireshark works perfectly), text change to white and it's unreadable. I tried to change color scheme in Wireshark, and System Settings, but nothing works:
![screenshot_20170611_153455](https://user-images.githubusercontent.com/17646853/27026535-597fd402-4f5e-11e7-83a9-8259191d3ca8.png)

**Comment by enkeyz** [comment]
I need some help guys.

**Comment by SmartFinn** [comment]
I checked a lot of combinations but could not reproduce this bug.

Linux Mint 18
Wireshark 2.0.2

**Comment by enkeyz** [comment]
I'm using Kubuntu 17.04 with Plasma 5.9.4.Qt version of Wireshark is 2.2.4. And since I wrote about this bug, I reinstalled Kubuntu on my desktop pc, and installed your theme, but it's the same. Default KDE theme - breeze - is working perfectly btw.

So my exact steps are:
- installed your theme using ppa
- Settings -> Workspace theme -> Arc-Dark
- Settings -> Colors -> Arc-Dark
- Settings -> Application style -> Widget style -> kvantum
- Kvantum Manager -> Change/Delete theme -> ArcDark

**Comment by SmartFinn** [comment]
Works as expected:
 
![screenshot from 2017-05-26 14-40-10](https://cloud.githubusercontent.com/assets/819186/26493291/469c20d8-4221-11e7-860e-05bcb93f904c.png)

**Comment by enkeyz** [comment]
I don't know what is the issue then. Only this application is affected. I'm not using any not-offical ppas, except yours.

**Comment by SmartFinn** [comment]
@enkeyz open an issue at https://github.com/tsujan/Kvantum/issues. The bug is affected all Kvantum themes.

**Comment by enkeyz** [comment]
You told me 30 minutes ago, you have no problem, and attached screenshots. So what now?

**Comment by SmartFinn** [comment]
Earlier I testing without Kvantum. You too late added details to reproduce the bug.

**Comment by enkeyz** [comment]
Ah, that was my fault then. Sorry bro.

**Comment by enkeyz** [comment]
One of the bugs now fixed in the latest Kvantummanager:
![screenshot_20170612_103356](https://user-images.githubusercontent.com/17646853/27026443-0ec13870-4f5e-11e7-8733-4e2a3a6da479.png)
