### ISSUE TITLE
Restore old Makefile for system-wide installation

### ISSUE THREAD

**Issue by cryzed** [PapirusDevelopmentTeam/arc-kde#4]
Would you consider restoring the old Makefiles (merging and adapting them for this project) that used to exist in the old repository locations:

- https://github.com/varlesh/Arc-KDE
- https://github.com/varlesh/Arc-Dark-KDE

for an easy system-wide installation? Currently I only see an option to install and remove it from the user's home.

**Comment by SmartFinn** [comment]
Makefile is not supported anymore. I added the install-arc-kde-root.sh, not sure that all paths are correct, can you tested it?

### remove
```
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/arc-kde/master/remove-arc-kde.sh | sh
```

### install
```
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/arc-kde/master/install-arc-kde-root.sh | sh
```

**Comment by varlesh** [comment]
install on root directory not needed, because all worked fine from home and this more safe!
root directory need for maintainers only - Papirus not have maintainers now, all third-party repos discontinued and not supported!

**Comment by varlesh** [comment]
Ouh i'm forgot sudo/kdesudo... Ok root-install need

**Comment by cryzed** [comment]
Most distributions will attempt to turn this into a package installable by package manager, for example pacman/makepkg. To easily create such a package one needs to be able to specify the `DESTDIR`, which is possible using a Makefile. I don't expect anyone to actually run the install script as a root, I'd much rather rely on my package manager's mechanics.

**Comment by varlesh** [comment]
We not have maintainers and support only git repo. Sorry, but now create package it's not our problem.
All install paths available on scripts

**Comment by cryzed** [comment]
I understand, thanks for creating Arc KDE.

**Comment by varlesh** [comment]
@cryzed You can open new PR and add new universal makefile if you needed

**Comment by cryzed** [comment]
I would if I was familiar at all with creating them. I know how to use them but not create them, Makefiles are usually used for C/C++ projects which I don't personally use at all unfortunately.

For now someone has already taken up the task of creating an easily installable package for Arch Linux [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=arc-kde-git).

**Comment by varlesh** [comment]
Sorry, i'm too :) I can only draw

**Comment by varlesh** [comment]
If you fear run install script for root - you can use script for home, it's safe.

**Comment by varlesh** [comment]
Or install manual - clone repo, check files and copy folders

**Comment by cryzed** [comment]
No worries, I'm using [this](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=arc-kde-git), which creates a package that is completely installable and removable system-wide. Thanks for Arc KDE :)!
