### ISSUE TITLE
Hitbox of 'close-window' Button

### ISSUE THREAD

**Issue by ghost** [PapirusDevelopmentTeam/arc-kde#40]
On pretty much all (preinstalled) themes, being it Windows 'default' or under Linux 'KDE breeze' it is very comfortable to be able to quickly drag the mouse to the top-right corner (where the close button is) and press to close a window.

On Arc-KDE there is a small dead-zone just around the close-button so you actually have to hit the button kinda of more precise if you want to close a window. I've found myself wanting to crush my mouse for 'it's inaccuracy' quite some times now =/

**Comment by SmartFinn** [comment]
#12

**Comment by ghost** [comment]
fml, overlooked the 'closed' section in the issue tracker.
