### ISSUE TITLE
Remove dependencies on konversation and yakuake

### ISSUE THREAD

**Issue by anewuser** [PapirusDevelopmentTeam/arc-kde#41]
On a clean KDE Neon install, this what is added with `arc-kde`:

>The following NEW packages will be installed:
  arc-kde konversation konversation-data kvantum yakuake

Can you make the .deb package just place the theme files for those applications in the appropriate directories without forcing people to install their packages?

**Comment by SmartFinn** [comment]
Those packages aren't dependencies, those are recommended packages. You can ignore these packages using the following command:

```
sudo apt-get install --no-install-recommends arc-kde
```

If you think it's a bad way, I can move `konsole`, `konversation` and `yakuake` into Suggests section.

**Comment by anewuser** [comment]
I see. I assumed they were set as dependencies because they are listed to be installed automatically by default. It'd be a good idea to move them to the Suggests section then.
