### ISSUE TITLE
Opaque menu border in Neon with Qt 5.9

### ISSUE THREAD

**Issue by abhnvkmr** [PapirusDevelopmentTeam/arc-kde#42]
i had installed Arc-KDE and Kvantum from papirus PPA. Yesterday Qt 5.9 was pushed to Neon User edition and now the menu borders look like this

![screenshot_20170620_175848](https://user-images.githubusercontent.com/1756451/27333051-06e9e726-55b4-11e7-8e02-cf6b7ccedf10.png)

**Comment by varlesh** [comment]
Thx for report, it's reproduced on other kvantum themes?

**Comment by varlesh** [comment]
I'm now try Arc Dark Transparent with Qt 5.7 and Qt 5.9 (with update) on Live KDE Neon and not confirm this:
![screenshot_20170620_194628](https://user-images.githubusercontent.com/8083855/27353368-416c79f6-55f3-11e7-8a70-63a6f66be62f.png)
![screenshot_20170620_195804](https://user-images.githubusercontent.com/8083855/27353600-19e29478-55f4-11e7-84fb-a2cb63b547ef.png)

Try remove temp files on **~/.cache** directory and relogin?

**Comment by abhnvkmr** [comment]
Still happening with other Kvantum themes. I also cleared .cache sans non-KDE folders.

Still I am fairly sure that it is a configuration issue because it's not happening for new users. Only for users that existed before I upgraded to 5.9.

**Comment by varlesh** [comment]
Sometime i see this bug too, but only for desktop menu **right click > Add Panel**. But it's not reproduced always - now all fine showing...
Also i'm use version 0.10.4, try this:
https://github.com/tsujan/Kvantum/releases/download/V0.10.4/kvantum_0.10.4-ubuntuLTS_amd64.deb
This happened only for desktop widget menu for you or for another menus too (apps, other widgets and etc)?
@tsujan you have ideas?

**Comment by varlesh** [comment]
Also notice, for **right click > add panel** not used shadows. For example, theme KvAmbiance:
![screenshot_20170621_115035](https://user-images.githubusercontent.com/8083855/27373209-789aebf8-5678-11e7-8e27-8e620732752a.png)

**Comment by varlesh** [comment]
@tsujan i reproduce this bug (it's happened not always):
![image](https://user-images.githubusercontent.com/8083855/27373776-9fd227de-567a-11e7-9579-e55244ab30c2.png)

**Comment by tsujan** [comment]
I can't reproduce this but I recompiled Kvantum as soon as Qt was upgraded to 5.9 on my system. So, I recommend a recompilation against Qt 5.9.

**Comment by tsujan** [comment]
There's also another possibility. Lack of shadow usually means lack of compositing when a menu is created for the first time. The plasma may be started a few milliseconds before the compositor. Can you see the issue with applications that aren't related to Plasma?

**Comment by varlesh** [comment]
No, for me it's happened for only desktop widget > add panel menu sometime.
I try recompile kvantum with new packages from Neon PPA

**Comment by tsujan** [comment]
OK, if it only happens with Plasma, it should be about the startup order, as I mentioned above. However, recompilation against 5.9 is a good idea.

If you see those shadowless menus in any app NOT related to Plasma, please tell me!

**Comment by varlesh** [comment]
I'm now use your package 0.10.4 from release and this happened randomly. I think you right with:
>Lack of shadow usually means lack of compositing when a menu is created for the first time. The plasma may be started a few milliseconds before the compositor. 

See, now all fine and shadows too:
![image](https://user-images.githubusercontent.com/8083855/27382533-70a523e4-5698-11e7-926e-01c7e64c0f1a.png)
Maybe need add sleep option some seconds for start?

**Comment by varlesh** [comment]
@abhinavk Please test with new git version (compiled with Neon PPA's):
https://launchpad.net/~varlesh-l/+archive/ubuntu/test/+build/12783385/+files/kvantum_0.10.4ubuntu16.04_amd64.deb

**Comment by varlesh** [comment]
oops, sorry... for launchpad not available add repos from neon, because packages hosted on another server.
Compiled with Qt 5.5 (from ubuntu ppa)

**Comment by varlesh** [comment]
You right @tsujan , because when i change engine kvantum > breeze > kvantum. All looks fine.
@abhinavk Try this

**Comment by abhnvkmr** [comment]
I installed the .deb and it now looks fine.

**Comment by tsujan** [comment]
@varlesh I logged into KDE again and, at last, saw it:

![plasma1](https://user-images.githubusercontent.com/981076/27382811-aca116d2-569d-11e7-91d8-b2e105065768.png)

This is not about compositing; the submenu is composited but has no shadow.

Kvantum includes a workaround for some rare cases, where a stylesheet containing "padding" is applied to a menu. In such cases, Kvantum removes the shadow because, most probably, the stylesheet would interfere with the shadow size and would make it ugly. Such cases are caused by mistakes in the app code.

However, I'm confused by the randomness: If there's a stylesheet, it should be always there.

**Comment by varlesh** [comment]
See dev comment, it's happened because plasma started a few milliseconds before the compositor.
Temporary solution - reenable kvantum engine.

**Comment by varlesh** [comment]
>This is not about compositing; the submenu is composited but has no shadow.
Kvantum includes a workaround for some rare cases, where a stylesheet containing "padding" is applied to a menu. In such cases, Kvantum removes the shadow because, most probably, the stylesheet would interfere with the shadow size and would make it ugly. Such cases are caused by mistakes in the app coding.
However, I'm confused by the randomness: If there's a stylesheet, it should be always there.

But see my previous screen , border with shadows https://github.com/PapirusDevelopmentTeam/arc-kde/issues/42#issuecomment-310053472
It's very strange

**Comment by tsujan** [comment]
Yes, your test confirms the compositing hypothesis rather than the above one: in my screenshot, the menu is composited because compositing is present but it got its shadow size *before* compositing was enabled. Plasma has its weird bugs....

**Comment by tsujan** [comment]
Actually, the workaround I mentioned above is only for context menus of line-edits. Therefore, the compositing being started too late is the best explanation of this case :)

**Comment by varlesh** [comment]
Ok, @tsujan thx for help. Closed.
PS: KDE bugs infinitely :)

**Comment by tsujan** [comment]
> because when i change engine kvantum > breeze > kvantum. All looks fine.

You're completely right. I did the same thing and everything is OK:

![plasma2](https://user-images.githubusercontent.com/981076/27383683-54c29874-56a1-11e7-818b-684092d9b8ed.png)
