### ISSUE TITLE
Slack tray icons?

### ISSUE THREAD

**Issue by francoism90** [PapirusDevelopmentTeam/arc-kde#43]
If possible; thanks. :)

**Comment by varlesh** [comment]
use [hardcode-tray](https://github.com/bil-elmoussaoui/Hardcode-Tray)

**Comment by varlesh** [comment]
Also KDE have bug rendering and size for electron and gtk-apps on tray. See this:
https://bugs.kde.org/show_bug.cgi?id=366062
