### ISSUE TITLE
Problem with some App after last update

### ISSUE THREAD

**Issue by thymbahutymba** [PapirusDevelopmentTeam/arc-kde#44]
After last update some app give me problem with this theme, if i change with breeze or breeze dark there are no problem. I post some image to let you show:
![screenshot_20170630_1802](https://user-images.githubusercontent.com/23526758/27744100-99c85552-5dbe-11e7-8b05-907605e282e1.png)
![screenshot_20170630_1759](https://user-images.githubusercontent.com/23526758/27744102-9a35e324-5dbe-11e7-8fb5-09abf9971799.png)
I'm trying to change every settings but noone works correctly. How i teel before, with breeze theme (dark and light) i have no problem, how i can resolve this?

**Comment by varlesh** [comment]
You run kvantummanager? It's not Kvantum theme. Logs show errors?

**Comment by thymbahutymba** [comment]
Logs don't tell me nothing... Return to breeze them solved problem xD

**Comment by SmartFinn** [comment]
This issue is closed because no further activity occurs. To reopen the issue just add the requested information.
