### ISSUE TITLE
Last update broke audio tray icon in Arc-Color

### ISSUE THREAD

**Issue by marhkb** [PapirusDevelopmentTeam/arc-kde#45]
After I did update today I have no audio tray icon on two machines in Plasma.

![no-audio](https://user-images.githubusercontent.com/3630213/27748744-d98e5d3c-5dd0-11e7-9859-a49372120f08.png)

**Comment by varlesh** [comment]
How you install arc color?

**Comment by marhkb** [comment]
through https://aur.archlinux.org/packages/arc-kde-git/

**Comment by varlesh** [comment]
I'm delete 32px volume icon (but 22px available), because with light theme used not Colorized icons.
See this https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/529

>through https://aur.archlinux.org/packages/arc-kde-git/

Try delete plasma cache on:
`rm -rf ~/.cache/plasm*`
 relogin and apply theme again

**Comment by marhkb** [comment]
that worked. thanks.

**Comment by varlesh** [comment]
For notifications now Brightness and Volume used colorize KDE colors... but for touchpad this not worked, because touchpad not use icon from Plasma theme, used from system icon theme - it's upstream bug
