### ISSUE TITLE
Highlight active button when using keyboard with Kvantum and Qt-based applications

### ISSUE THREAD

**Issue by maxigaz** [PapirusDevelopmentTeam/arc-kde#48]
When using one of the Arc themes for Kvantum, the active button (which can be changed with the arrow keys or TAB on the keyboard) is never highlighted, which makes keyboard navigation difficult. I only have this problem with Qt-based applications.

However, when I'm in a GTK+ application or using the built-in Kvantum theme, dotted lines indicate the active button, which would be the expected behaviour.

I'm using Manjaro Linux with KDE Plasma 5.10.3 and Qt 5.9.1.

**Comment by varlesh** [comment]
thx for report, fixed soon

**Comment by varlesh** [comment]
@maxigaz please check

**Comment by maxigaz** [comment]
It looks like it's working. (I also had to reset the settings for the Arc Dark theme in Kvantum Manager or choose one of the other Arc themes with no modified settings.) Thank you very much!
