### ISSUE TITLE
Eclipse themes not working

### ISSUE THREAD

**Issue by sdfg2** [PapirusDevelopmentTeam/arc-kde#49]
Hello,

Thank you for all your work.

I'm just setting up a new eclipse environment, and thought I'd take advantage of your wonderful work, however it doesn't seem to work.  I followed the instructions, and the EPF imports ok, but it doesn't apply the colours:

![screenshot_20170806_233445](https://user-images.githubusercontent.com/5736478/29007641-9683d570-7aff-11e7-9d79-452cb7b01d21.png)

I tried restarting with no luck.  Do I need to force GTK 2 for this to work?  I know that will then use the system GTK (I remember having trouble with other things before) but I know that's not the ideal solution if the GTK3 theme can be bludgeoned into submission :-)

Edit:  I mistyped the topic, but can't change it, sorry.

**Comment by varlesh** [comment]
Hi. Sorry, but i'm not make this theme and not remember who doing this...

**Comment by varlesh** [comment]
@AD2076 hi, you create?

**Comment by AD2076** [comment]
i created this theme, will have a look at the issue as soon as I'm back from vacation. on the beach atm :)

**Comment by varlesh** [comment]
@AD2076 Ok! Pleasant rest :)

**Comment by sdfg2** [comment]
@AD2076 hope you had a nice vacation, have you had a chance to look at this? I had a quick look but don't know anything about theming gtk.

**Comment by AD2076** [comment]
It's not gtk theming, just some configs for the Jeeeyul's plugin. Which Eclipse version are you using?
OS? Plugin version?

**Comment by sdfg2** [comment]
I'm using Eclipse Oxygen (4.7.0) on Arch linux, Jeeeyul's Themes 2.3.0.I20151022-090442
