### ISSUE TITLE
New package version scheme bug

### ISSUE THREAD

**Issue by domker** [PapirusDevelopmentTeam/arc-kde#50]
Hi,
After last changes version scheme in PKGBUILD, Octopi still shows that the package is NOT up to date.
https://i.imgur.com/2Z9W2YM.png

I think issue is here in PKGBUILD:
```
pkgver() {
    cd "${srcdir}"
    printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

```
Becouse after makepkg -s "pkgver" is changed to "r."

**Comment by varlesh** [comment]
Write about that on AUR. We support only PPA.

**Comment by SmartFinn** [comment]
Hi,

arc-kde-git<sup>AUR</sup> is an unofficial package, try to report the problem to the package maintainer here https://aur.archlinux.org/packages/arc-kde-git/
