### ISSUE TITLE
Suggestion : Battery Icon

### ISSUE THREAD

**Issue by zazatek** [PapirusDevelopmentTeam/arc-kde#53]
Hi, 

the theme is very very great, but I have some problem with the battery :/

It's very difficult to see if the pc is charging or not, can we do something ? 

Without charging : https://vgy.me/2xAML3.png

With charging : https://vgy.me/hLGqxS.png

This is the only problem with this theme, we can't know the position of the battery.

And, do u think that we can do a red icon when the battery is critical ?

Thanks!

**Comment by varlesh** [comment]
Hi, sorry but we not use red color on plasma theme. For notification and critical messages used blue color #5294e2ff 
i found only 2 solution:
1- use blue color
2- add stroke 0.5 px
![2017-08-20 07-17-02](https://user-images.githubusercontent.com/8083855/29491808-f0dd7af8-8577-11e7-847b-7ccb050bdf6e.png)

**Comment by zazatek** [comment]
I think that the blue color is better for eyes. But the Stroke is more correlated with the theme. What do you think ?

**Comment by varlesh** [comment]
For Arc Color blue it's Highlight plasma color and maybe with combination Text color  - this could be not good (with different color scheme)

**Comment by varlesh** [comment]
I think stroke variant better, because universal for Arc Dark and Arc Color too

**Comment by zazatek** [comment]
Ok nice, I am using Arc Dark. 

Do you know how can  I add the Stroke ? (I am on Fedora Plasma).

**Comment by varlesh** [comment]
> Do you know how can I add the Stroke ? (I am on Fedora Plasma).

Not needed i'm fixed this soon on Master branch

**Comment by zazatek** [comment]
Ok thanks

**Comment by varlesh** [comment]
@zazatek Please check

**Comment by varlesh** [comment]
Final result not like me, i'm del stroke and colorize AcAdapter object to blue:
https://github.com/PapirusDevelopmentTeam/arc-kde/commit/0009a466f06f37e1d6fb88ab6518b7d636e938cc
![2017-08-20 08-54-43](https://user-images.githubusercontent.com/8083855/29492209-3c6d3316-8585-11e7-83c7-d84e5d7f25d9.png)
