### ISSUE TITLE
Battery icon missing in arc color theme

### ISSUE THREAD

**Issue by ghost** [PapirusDevelopmentTeam/arc-kde#55]
In Arc color theme battery icon in system tray is not visible. 
![screenshot_20170901_144821](https://user-images.githubusercontent.com/31536583/29964896-111a600e-8f25-11e7-9bd8-aca1bde2c020.png)

Arc dark works fine though.
![screenshot_20170901_145445](https://user-images.githubusercontent.com/31536583/29965077-a7315048-8f25-11e7-9e22-895c000f72a4.png)

**Comment by varlesh** [comment]
`rm -rf ~/.cache/plasm*` logout and apply theme again

**Comment by varlesh** [comment]
@arasbill Please check with last commit

**Comment by ghost** [comment]
yes latest update fixed it. thanks a lot.

**Comment by varlesh** [comment]
@arasbill  I'm fix more things for Arc Color, please update.
For example, Norway color-scheme
![image](https://user-images.githubusercontent.com/8083855/30001770-d0f62848-90a8-11e7-9c88-0ad3b8adb133.png)
