### ISSUE TITLE
Desktop pager's window outlines hidden by highlight color

### ISSUE THREAD

**Issue by will8211** [PapirusDevelopmentTeam/arc-kde#56]
Hi! Love the theme, it's working out great for me. One little hickup though! I like to use a the desktop pager widget on my panel. However, the outlines of opened windows on the pager are now hidden behind the blue highlighting of both the active desktop, and any desktop that is hovered over with the mouse.

edit: I installed from the ubuntu PPA, so perhaps this is already fixed in the latest build?

**Steps to reproduce:**
-Add a desktop pager widget to the panel.
-Add a virtual desktop so there are at least two.
-Open any application.

**Expected results:**
-On the pager, the rectangle representing the current desktop shows the outline of the opened window.

**Actual results:**
-The rectangle showing the current desktop is completely blue, and no window outlines can be seen.
-The outlines of any open windows on other desktops are similarly hidden when the mouse hovers over pager rectangle representing that desktop.

Note: In the default Breeze theme, there is a blue highlight, but it is transparent, allowing the outlines (and icons, if they are turned on) to be seen.

KDE Plasma 5 version 5.10.5 
Distro: KDE neon
Arc-kde version: 20170903-95+pkg4~ubuntu16.04.1 (Installed from official PPA)

<img width="427" alt="kde_dark_issue" src="https://user-images.githubusercontent.com/12148797/30098232-a05baea2-9313-11e7-8dd1-a803084da1ce.png">

**Comment by varlesh** [comment]
Thx for report, but Highlight blue color not use opacity and stroke too - it's Arc style.

> outlines of any open windows

It's plasma draw i can't change this

**Comment by will8211** [comment]
Thanks for the quick reply! Too bad it can't be changed. ~~If I understand correctly, changing it would also change all highlights and hover-highlights in the theme?~~ edit: see fix below.

Could you possibly point me to where I can change this color to transparent on my system? I couldn't find any way to change the opacity in ~/.kde/share/apps/color-schemes/Arc\ Dark.colors

Is it one of the svg's in /.local/share/plasma/desktoptheme/Arc-Dark/widgets?

Thanks!

**Comment by varlesh** [comment]
@will8211 You can delete `pager.svg` from widgets folder on Plasma theme > will be used default Breeze pager.
Clear cache, relogin and apply theme again:
`rm -rf ~/.cache/plasm*`

**Comment by will8211** [comment]
Thanks, I'll try it out!

**Comment by will8211** [comment]
In case anyone wants it, here's the default pager.svg with transparency recolored to match the arc theme highlight color (#5294e2ff).
Depending on your installation, it will go in either
~/.local/share/plasma/desktoptheme/Arc-Dark/widgets
or
/usr/share/plasma/desktoptheme/Arc-Dark/widgets

As Varlesh mentions above, clear cache, relogin and apply theme again:
rm -rf ~/.cache/plasm*

[pager.zip](https://github.com/PapirusDevelopmentTeam/arc-kde/files/1289547/pager.zip)
