### ISSUE TITLE
Volume HUD in arc-dark plasma theme shows always the minimum

### ISSUE THREAD

**Issue by Tichy** [PapirusDevelopmentTeam/arc-kde#57]
![screenshot_20170907_000429](https://user-images.githubusercontent.com/2348771/30136812-f8692c1c-9360-11e7-8199-f97257202431.png)

See screenshot: when I change the volume, the HUD flashes for a fraction of second to the correct volume indication, then it returns to the minimum. The audio volume is correctly changed, so it's only a visual problem.
This doesn't happens with arc-color theme

KDE plasma 5.10.5
Framework: 5.37.0
QT: 5.9.1
Kernel: 4.12.10-1-ARCH
NVIDIA proprietary drivers on GTX 1060

**Comment by varlesh** [comment]
@Tichy 
> This doesn't happens with arc-color theme

It's strange, becaue widgets similar!

Maybe try change step volume?

I'm use 2% and not confirm this:

![image](https://user-images.githubusercontent.com/8083855/30152043-e10d1940-93c2-11e7-9b67-435559a35fcc.png)

**Comment by Tichy** [comment]
Il 2017-09-07 09:51 Alexey Varfolomeev ha scritto:

> @Tichy [1]
> 
>> This doesn't happens with arc-color theme
> 
> It's strange, becaue widgets similar! 
> 
> Maybe try change step volume? 
> 
> I'm use 2% and not confirm this:

I have no problems with a different PC. 

KDE Plasma: 5.9.5 

Framework: 5.31.0 

QT: 5.7.1 

Kernel: 4.10.0-33 (Kubuntu) 

VGA Intel integrated 

Maybe, it could depend on the software versions, or VGA drivers. When
I'll be back to the other PC, I will try to change the rendering engine
from OpenGL 3.1 to OpenGL 2.0 

Links:
------
[1] https://github.com/tichy

**Comment by varlesh** [comment]
Maybe... now on my nvidia render wrong bugged too...
@Tichy you can check [this bug](https://bugs.kde.org/show_bug.cgi?id=384457) for Aurorae?

![image](https://user-images.githubusercontent.com/8083855/30154465-0fa02f88-93cb-11e7-819d-3b3e573f36b0.png)

**Comment by varlesh** [comment]
@Tichy See on Nvidia blurred button icons, but on Intel all fine

**Comment by Tichy** [comment]
Il 2017-09-07 10:50 Alexey Varfolomeev ha scritto:

> Maybe... now on my nvidia render wrong bugged too...
> @Tichy [1] you can check this bug [2] for Aurorae?

Sure. As soon as I get back home. ;) 

Links:
------
[1] https://github.com/tichy
[2] https://bugs.kde.org/show_bug.cgi?id=384457

**Comment by varlesh** [comment]
Now, i'm commit single variant for `bar_meter` widget and we can check this...

**Comment by varlesh** [comment]
Video with GTX 1050ti and last commit:
https://youtu.be/BeDIeQW4gaU

**Comment by varlesh** [comment]
Also for better perfomance and fix tearing i use this settings on Plasma 5.

**Systemsettings - Display - Providing Effects**:
- Engine - OpenGL 2.0
- Vsync - Reuse

**/etc/profile.d/kwin.sh**:
```
export __GL_YIELD="USLEEP"
```
**nvidia-settings - OpenGL Settings**:
 - disable "Sync to VBlank"
 - enable "Allow Flipping"

**Comment by Tichy** [comment]
Hi! I did some test. I can confirm that the volume issue is fixed on my setup with your last commit.
I can't confirm the blurred icons in the aurorae theme with nvidia: they appear sharp to me.
My settings are:
Engine: OpenGL 3.1
Vsync: Auto
I have the same kwin.sh script and nvidia settings.

**Comment by Tichy** [comment]
Fixed in my setup. Thank you ;)

**Comment by varlesh** [comment]
@Tichy You check [this bug](https://bugs.kde.org/show_bug.cgi?id=384457) on NVidia?

**Comment by varlesh** [comment]
Please show screenshot with Nvidia GPU.
I don't understand why on my GPU this happened...

**Comment by Tichy** [comment]
Sure. Screenshots with dark and light themes
![screenshot_20170908_181443](https://user-images.githubusercontent.com/2348771/30220958-d278b04c-94c1-11e7-9492-d1777e705bf9.png)

![screenshot_20170908_181420](https://user-images.githubusercontent.com/2348771/30220982-e59586fa-94c1-11e7-9d56-2c4343ae4271.png)

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/30224400-bf0cc8a4-94df-11e7-9c26-690d6265dee2.png)
@Tichy you use 384.69 version?

**Comment by Tichy** [comment]
In data venerdì 8 settembre 2017 19:51:18 CEST, Alexey Varfolomeev ha scritto:
> ![image](https://user-images.githubusercontent.com/8083855/30224400-bf0cc8a4
> -94df-11e7-9c26-690d6265dee2.png) @Tichy you use 384.69 version?

Yes. 384.69-2 (ArchLinux)

**Comment by varlesh** [comment]
@Tichy Sorry for my molestation, but you config anything tools on plasma? Maybe DPI settings or on other...
Can post xorg.conf please?

**Comment by Tichy** [comment]
In data venerdì 8 settembre 2017 20:08:59 CEST, Alexey Varfolomeev ha scritto:
> @Tichy Sorry for my molestation, but you config anything tools on plasma?
> Maybe DPI settings or on other... Can post xorg.conf please?

Nothing relevant in xorg (just keyboard and mouse settings).
DPI is 96, also set in .Xresources

Xft.dpi:       96
Xft.antialias: true
Xft.hinting:   true
Xft.autohint:  false
Xft.hintstyle: hintslight
Xft.lcdfilter: lcddefault
Xft.rgba:      rgb

Compositing settings in KDE are

Animation speed at half scale
Scale method accurate
Rendering backend OpenGL 3.1
Tearing prevention Automatic
Keep window thumbnails only for shown windows
Allow applications to block compositing (on)

**Comment by varlesh** [comment]
@Tichy WOW It's worked!!! Big thx :+1: 
**~/.Xresources:**
```
Xft.dpi:       96
Xft.antialias: true
Xft.hinting:   true
Xft.autohint:  false
Xft.hintstyle: hintslight
Xft.lcdfilter: lcddefault
Xft.rgba:      rgb
```
![image](https://user-images.githubusercontent.com/8083855/30231389-b46ae270-94fb-11e7-9fa8-a3dc0ad73b8a.png)
