### ISSUE TITLE
New version Kvantum Themes

### ISSUE THREAD

**Issue by varlesh** [PapirusDevelopmentTeam/arc-kde#58]
I'm redesign Kvantum themes, maybe add Arc Darker version.
But i'm confused with menuitem widget....
Without global menu on Window apps looking fine:
![image](https://user-images.githubusercontent.com/8083855/30209617-06375b8a-94aa-11e7-8762-b0321b7c4364.png)
But if enable global app menu widget, it's looking ugly :(
![image](https://user-images.githubusercontent.com/8083855/30209649-3edec036-94aa-11e7-985f-4170eb77e5ea.png)

**Comment by varlesh** [comment]
Dolphin vs Nautilus:
![image](https://user-images.githubusercontent.com/8083855/30209744-96e2fe78-94aa-11e7-9bdd-258dc0955c09.png)

**Comment by varlesh** [comment]
@SmartFinn Сереж привет. У тебя юнити? Глянь как клементин смотрится с арк дарком если не сложно

**Comment by varlesh** [comment]
Конкретно интересует бэкграунд вкладок

**Comment by SmartFinn** [comment]
@varlesh Привет!

Выглядит еще более уродливо как по мне:

![screenshot from 2017-09-08 14-42-23](https://user-images.githubusercontent.com/819186/30210153-1a02432e-94a4-11e7-8cf3-c7d2fa5d2430.png)

**Comment by varlesh** [comment]
Еще вот косяк - это отличия GTK3 и GTK2:
![image](https://user-images.githubusercontent.com/8083855/30210222-d73c5788-94ac-11e7-9663-16a638ecf27f.png)
Смотри в GTK3 и GTK2 кнопка наведения одна и та же, но кнопка нажатия в GTK3 синяя, а в GTK2  темная:
![image](https://user-images.githubusercontent.com/8083855/30210294-1aa06910-94ad-11e7-9179-f039e41d927d.png)
И как рисовать?

**Comment by varlesh** [comment]
Не понимаю, почему он не нарисовал обе синие?!

**Comment by SmartFinn** [comment]
Темная для pressed больше подходит.

**Comment by SmartFinn** [comment]
Но делать прийдется синюю :)

**Comment by varlesh** [comment]
Так в GTK3 pressed синяя:
![image](https://user-images.githubusercontent.com/8083855/30210399-9c7d0592-94ad-11e7-89df-06c78a103cff.png)
Скрин наутилуса

**Comment by varlesh** [comment]
сделю синюю кароче

**Comment by varlesh** [comment]
без меню, окна уродско выглядят:
![image](https://user-images.githubusercontent.com/8083855/30210561-27cf4790-94ae-11e7-8718-dc0913a68eb6.png)

**Comment by varlesh** [comment]
За то GTK2 с меню выглядят отлично терь ))
![image](https://user-images.githubusercontent.com/8083855/30210630-59d78f36-94ae-11e7-8f02-7d97e8e3ac65.png)

**Comment by SmartFinn** [comment]
@varlesh 

> без меню, окна уродско выглядят:

так в оригинальной теме также. Спасает что в GTK3 меню не встречается.

**Comment by varlesh** [comment]
> так в оригинальной теме также. Спасает что в GTK3 меню не встречается.

Ну да, я так и хотел... ближе к оригиналу.
Думаю мож еще Arc Darker сделать. А все версии Transparent делетнуть (в архив)

**Comment by varlesh** [comment]
Толку от этой transparent нету, так как GTK2 и GTK3 его не поддерживают в кедах

**Comment by SmartFinn** [comment]
@varlesh 

> А все версии Transparent делетнуть (в архив)

Они мне всегда сломаными казались.

> Думаю мож еще Arc Darker сделать

Она только для Kvantum, или версия для Plasma тоже будет?

**Comment by varlesh** [comment]
Ток для квантума, для плазмы не получится, там класс popup-menu отсутствует.

**Comment by varlesh** [comment]
@SmartFinn Бляха, какое все разное жесть.
Глянь 3 приложения и у всех разные цвета:
![image](https://user-images.githubusercontent.com/8083855/30219971-d6192c92-94ce-11e7-954b-f83bd2e9500a.png)

**Comment by varlesh** [comment]
вот хз какой цвет рисовать...
![image](https://user-images.githubusercontent.com/8083855/30220079-2a682942-94cf-11e7-916a-8a067112a1e2.png)

**Comment by varlesh** [comment]
если брать для бэкграунда `#353945`, то GTK2 по другому выглядят у них `#383c4a`.
если брать для бэкграунда `#383c4a`, то GTK3 по другому выглядят у них `#353945`.

**Comment by varlesh** [comment]
Тут кароче либо под GTK2 рисовать, либо под GTK3.... я хз как еще

**Comment by SmartFinn** [comment]
@varlesh к GTK3 все приведи, я думаю под него в первую очередь пилили.

**Comment by varlesh** [comment]
Вкладки не получится сделать, а жаль:
![image](https://user-images.githubusercontent.com/8083855/30220406-547ae6b0-94d0-11e7-81a7-8b35e2a77c98.png)

**Comment by SmartFinn** [comment]
Ага, смотрится бедненько.

**Comment by varlesh** [comment]
Там путь мешает

**Comment by varlesh** [comment]
Без вкладок в принципе отлично

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/30220649-39826c06-94d1-11e7-9513-5368603c5c0d.png)
