### ISSUE TITLE
Arc-DarkTransparent gone from kvantummanager after update

### ISSUE THREAD

**Issue by maxiride** [PapirusDevelopmentTeam/arc-kde#60]
This morning I received an update via apt (KDE Neon here) and the Arc DarkTransparent is now missing from the kvantum manager.

Is there something wrong in my installation?
I installed the them via apt install arc-kde

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/arc-kde/issues/59

**Comment by nerdius** [comment]
@Maxiride Check out [this fork](https://github.com/giogziro95/arc-kde). I won't be updating it frequently, but, at least, it's usable.

**Comment by nerdius** [comment]
@varlesh There's an issue I'm having with the older version... I forked your repo, reverted back to e06279795dc92c02d8431c263d93d798c9acedd5, and updated the scripts and the readme as needed, but the text fields on the desktop theme have blue backgrounds:

![Krunner](https://user-images.githubusercontent.com/2781117/30272200-681d943e-9704-11e7-9bc6-6ce86e0d974f.png)

Also, there's an issue with the background of _Active connections_ and _Available connections_ within the network manager plasmoid:

![Networks plasmoid](https://user-images.githubusercontent.com/2781117/30272264-b439f786-9704-11e7-8529-0f7c76eb91ab.png)

A few days ago, this wasn't like this. If this is not an issue with my setup, can you please tell me in which commit has this been changed? I'll have a look at the diff and sort it out myself.

Thanks!

**Edit:** Also, I've noticed that the arrows that indicate sorting (ascending/descending) aren't visible in the list headers:

![KSysGuard](https://user-images.githubusercontent.com/2781117/30273995-8a8323ce-970c-11e7-8e72-81a8a2467ccb.png)

**Comment by varlesh** [comment]
@giogziro95 Blue background used for new version too, because initialy Arc Dark Colors have wrong colors an more bugs.
You can compare colors and check this, extract to ~/.local/share/color-schemes [color-schemes.tar.gz](https://github.com/PapirusDevelopmentTeam/arc-kde/files/1293215/color-schemes.tar.gz)
Arrows not exist on old Kvantum themes, need update this.

**Comment by varlesh** [comment]
@giogziro95 See on up preview - it's Arc Dark OLD PLASMA colors:
![image](https://user-images.githubusercontent.com/8083855/30284838-2109312e-972d-11e7-843c-dd36ca274d59.png)
And NEW colors:
![image](https://user-images.githubusercontent.com/8083855/30284870-47ead860-972d-11e7-83b7-b1a2c76eb51c.png)

**Comment by varlesh** [comment]
lineedit widget will be fixed soon https://github.com/PapirusDevelopmentTeam/arc-kde/issues/61
