### ISSUE TITLE
Issues with ArcDark 

### ISSUE THREAD

**Issue by ArchangeGabriel** [PapirusDevelopmentTeam/arc-kde#64]
First, the menu is still transparent, not sure whether that’s intended or not.

![arcdark_transparency](https://user-images.githubusercontent.com/490531/30333107-6cf40c1c-97dc-11e7-803a-f8ce843f2315.png)

Then, colors of applications in task manager do not match the one of the taskbar while they do in ArcColor or Breeze for instance. Also, active application is underlined instead of overlined, which is not really beautiful. Finally, I prefer the greyed “mute” icon of ArcColor, couldn’t we have that too for ArcDark?

![arcdark_underline](https://user-images.githubusercontent.com/490531/30333109-6d0e0504-97dc-11e7-8860-80bf5462bf32.png)

**Comment by varlesh** [comment]
> Also, active application is underlined instead of overlined, which is not really beautiful

Why not?
if use full fill for button, blue icons bad will be seen.

Arc Dark Transparent plasma theme, Arc Color not. Mute icon have this style for notification widget with 32px size, try reduce panel size.

**Comment by ArchangeGabriel** [comment]
Well maybe it’s a matter of taste, but I much prefer the overline of ArcColor.

Panel size is at its minimum.

**Comment by varlesh** [comment]
not confirm this:
![image](https://user-images.githubusercontent.com/8083855/30412093-3eb854fc-9926-11e7-8a67-511c21014067.png)

**Comment by varlesh** [comment]
@ArchangeGabriel Try change icon size for panel on **Systemsettings-Icons** open **Additional** tab, choose **Panel** and set 22px.
