### ISSUE TITLE
hiccups with kontact

### ISSUE THREAD

**Issue by tomdavidson** [PapirusDevelopmentTeam/arc-kde#65]
Hello and thank you for this beautiful theme on KDE. I have some hiccups with kontact:

![image](https://user-images.githubusercontent.com/50412/30339367-09d0658e-97ac-11e7-94ff-a241b9851c8b.png)

**Comment by varlesh** [comment]
Your screenshot not use arc dark. It's breeze engine. i recommend use Kvantum engine.

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/30342113-9c4434e2-9809-11e7-8441-9a7d3ac9be79.png)
