### ISSUE TITLE
Spinner loading to open programs

### ISSUE THREAD

**Issue by arthurflor23** [PapirusDevelopmentTeam/arc-kde#66]
Currently, I upgraded arc-kde and noticed that the loading spinner stayed like this:
![loading-spinner](https://user-images.githubusercontent.com/11759042/30508975-5e32c1fa-9a7a-11e7-80d9-fa2a6cf9b9b7.png)

Is it normal? It looks like something went wrong. No offense (if is normal) 
:)

**Comment by varlesh** [comment]
it's busywidget, already redesign. Update from git.
 https://github.com/PapirusDevelopmentTeam/arc-kde/commit/5421b56683c053f44867c0d795ac04b5f8c30275
![image](https://user-images.githubusercontent.com/8083855/30509031-89f6b4a4-9ab6-11e7-9614-158ede56f4c1.png)

**Comment by arthurflor23** [comment]
Oh, awesome!

**Comment by ddulic** [comment]
Any option to disable this spinner?
Thanks.
