### ISSUE TITLE
Hard to read text in panels and launcher with Arc Dark plasma theme + Arc (bright) color scheme

### ISSUE THREAD

**Issue by Tichy** [PapirusDevelopmentTeam/arc-kde#67]
![spectacle lh4818](https://user-images.githubusercontent.com/2348771/30522231-21da1c7c-9bcd-11e7-81ee-c072d35aa9dc.png)

I used to have the dark plasma theme, but with light colorscheme. Before the last release, it worked fine, but after the upgrade it started to look as you can see in the screenshot.

However, all is fine with Dark + Dark theme and Color + "bright" theme.

**Comment by varlesh** [comment]
Already fixed, update from git
