### ISSUE TITLE
Arc Dark plasma theme: the desktop tools button keeps "jumping" when moved to a corner

### ISSUE THREAD

**Issue by Tichy** [PapirusDevelopmentTeam/arc-kde#69]
https://imgur.com/a/NMVgM 
See this video. When I put the tools button in a corner it keeps morphing between the large and the compact version.
This does not happens with Arc Color

**Comment by varlesh** [comment]
fixed https://github.com/PapirusDevelopmentTeam/arc-kde/commit/10bcb75689cea3229d27b53a11a744c87e74697a
