### ISSUE TITLE
In virtual desktop plasmoid, the active desktop's windows outlines are covered

### ISSUE THREAD

**Issue by Tichy** [PapirusDevelopmentTeam/arc-kde#71]
See screenshot:

Breeze Dark
![screenshot_20170927_085435](https://user-images.githubusercontent.com/2348771/30899844-e9d9d2c6-a361-11e7-8b7d-a852126dc817.png)

Arc Dark
![screenshot_20170927_085401](https://user-images.githubusercontent.com/2348771/30899864-0a557d84-a362-11e7-8109-802efc7f48a3.png)

**Comment by varlesh** [comment]
Arc not use transparent for Highlight color - it's style!

**Comment by varlesh** [comment]
And workspace actived - this not need, because you see this workspace now....

**Comment by varlesh** [comment]
Also Arc Color have transparent Highlight Pager

**Comment by Tichy** [comment]
I see. Somehow it looked to me like a bug, instead of something done on purpose.

**Comment by varlesh** [comment]
@Tichy Because window preview stroke (not pager stroke) draw plasmashell, i can't fix that.
I like this style:
![image](https://user-images.githubusercontent.com/8083855/30901424-bf7bbf32-a378-11e7-95d7-e09b584ebfbc.png)

**Comment by varlesh** [comment]
It's can fixed on Pager code only.
/usr/share/plasma/plasmoids/org.kde.plasma.pager/contents/ui/main.qml:
```
hoverEnabled: true

    function colorWithAlpha(color, alpha) {
        return Qt.rgba(color.r, color.g, color.b, alpha)
    }

    readonly property color windowActiveOnActiveDesktopColor: colorWithAlpha(theme.textColor, 0.6)
    readonly property color windowInactiveOnActiveDesktopColor: colorWithAlpha(theme.textColor, 0.35)
    readonly property color windowActiveColor: colorWithAlpha(theme.textColor, 0.5)
    readonly property color windowActiveBorderColor: theme.textColor
    readonly property color windowInactiveColor: colorWithAlpha(theme.textColor, 0.17)
    readonly property color windowInactiveBorderColor: colorWithAlpha(theme.textColor, 0.5)

    function action_addDesktop() {
        pagerModel.addDesktop();
    }
```

**Comment by varlesh** [comment]
Fixed code:
```
readonly property color windowActiveOnActiveDesktopColor: colorWithAlpha(theme.textColor, 0.6)
    readonly property color windowInactiveOnActiveDesktopColor: colorWithAlpha(theme.textColor, 0.35)
    readonly property color windowActiveColor: colorWithAlpha(theme.textColor, 0.5)
    readonly property color windowActiveBorderColor: colorWithAlpha(theme.textColor, 0.0)
    readonly property color windowInactiveColor: colorWithAlpha(theme.textColor, 0.17)
    readonly property color windowInactiveBorderColor: colorWithAlpha(theme.textColor, 0.0)
```
![image](https://user-images.githubusercontent.com/8083855/30901820-512730be-a37a-11e7-9a2e-54144644a7e6.png)

**Comment by varlesh** [comment]
@Tichy  See, change transparency only for `windowActiveBorderColor` & `windowInactiveBorderColor`.
It's looking better ))
