### ISSUE TITLE
window decoration misalignment

### ISSUE THREAD

**Issue by themike10452** [PapirusDevelopmentTeam/arc-kde#72]
I have an issue on freshly installed KDE Neon, the window border is 1 or 2 pixels off for some reason on both sides, I searched a lot and didn't find anything related to it. What can I do?

![image](https://user-images.githubusercontent.com/7006763/31908366-43c07c08-b83f-11e7-8db7-7ed8d59a25c5.png)
![image](https://user-images.githubusercontent.com/7006763/31908397-6776a140-b83f-11e7-98a0-c6b3f7781134.png)

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/adapta-kde/issues/21
