### ISSUE TITLE
Window Decorations - add more options

### ISSUE THREAD

**Issue by ghost** [PapirusDevelopmentTeam/arc-kde#73]
Currently, the Arc themes in System Settings > Application Style > Window Decorations have only one option, "Button Size". However, it would be nice to have: _title alignment,_ _spacing_, etc. Currently I find the spacing between buttons to be a bit too large, and because I have my buttons left aligned, it looks very strange having a center aligned title.

**Comment by varlesh** [comment]
Aurorae not have option for change title position - it's upstream issue.
Also i can't set title on right, because by default on KDE used buttons on right.
BUT, you can change this by manually on **/usr/share/aurorae/themes/Arc-Dark/Arc-Darkrc**:
```
TitleAlignment=Right
```
