### ISSUE TITLE
Tooltips with light text on light background under ArcDarker

### ISSUE THREAD

**Issue by gabrc52** [PapirusDevelopmentTeam/arc-kde#74]
Tooltips are almost unreadable when using the ArcDarker Kvantum theme

**Comment by varlesh** [comment]
I'm not confirm this:
![image](https://user-images.githubusercontent.com/8083855/34646058-df9eaabe-f377-11e7-8111-c27a66717c2e.png)
Plasma 5.11.5

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/34646117-4aea4eda-f379-11e7-9929-bfde5a7659b8.png)

**Kvantum 0.10.5**

**Comment by gabrc52** [comment]
![KSysGuard](https://user-images.githubusercontent.com/24363938/34684928-5a55fa9c-f46c-11e7-8f2c-323872336b9d.png)
![System Settings](https://user-images.githubusercontent.com/24363938/34684959-6f409d9a-f46c-11e7-8857-f2c66d067b25.png)

**Comment by gabrc52** [comment]
Apparently I had an old version of the theme applied. I had used the "Configure Active Theme" option in Kvantum Manager, which apparently just saves a copy of the theme with the changes instead of just saving the changed settings. 

To fix this, I selected the theme and deleted it from Kvantum Manager, which replaced it with the most recent version of the theme.
