### ISSUE TITLE
Weird disk space issue in Dolphin

### ISSUE THREAD

**Issue by tenten8401** [PapirusDevelopmentTeam/arc-kde#75]
Title says it all pretty much.
![image](https://user-images.githubusercontent.com/6174343/35198881-59e56e56-fec3-11e7-8e32-ac2868e74f5c.png)

**Comment by varlesh** [comment]
not confirm this:
![image](https://user-images.githubusercontent.com/8083855/35199185-3063405c-ff14-11e7-83f3-70ea7fc7de37.png)

Maybe you use KvArcDark? It's not my theme

**Comment by tenten8401** [comment]
I am using KvArcDark, because using Arc Dark makes the padding look off and the hover effects for regions don't work properly... I thought the Kvantum version was reccomended?
![peek 2018-01-21 17-10](https://user-images.githubusercontent.com/6174343/35199585-1c46fe4c-fece-11e7-8cf1-d119041d8028.gif)

**Comment by varlesh** [comment]
Hover effect not used on GTK Theme... Run nautilus and check (or another GTK app) And i don't like this.
Nevertheless KvArcDark - it's upstream theme. Open request on kvantum project

**Comment by tenten8401** [comment]
Oh, you're right. My bad.
