### ISSUE TITLE
In kali linux

### ISSUE THREAD

**Issue by meetcngh-sopho** [PapirusDevelopmentTeam/arc-kde#77]
Hello sir, i am cloning this repo in kali and run the .sh script and get installed 
Then tell me how to change the theme please

**Comment by varlesh** [comment]
Kali not use KDE

**Comment by varlesh** [comment]
https://distrowatch.com/search.php?ostype=Linux&category=All&origin=All&basedon=All&notbasedon=None&desktop=KDE&architecture=All&package=All&rolling=All&isosize=All&netinstall=All&language=All&defaultinit=All&status=Active#simple
