### ISSUE TITLE
Menu expanding icon in tree view, disappearing after selecting.

### ISSUE THREAD

**Issue by morali** [PapirusDevelopmentTeam/arc-kde#79]
[https://i.imgur.com/0oH8RGD.gifv](https://i.imgur.com/0oH8RGD.gifv)

As you can see on video, on tree view, this small triangle on the right is disappearing when selecting sub menu. Example shown is on Qt Creator, but the same is happening in file picker etc.

I'm using Arc theme and Kvantum engine. It doesn't happen on Arc Dark theme.

**Comment by varlesh** [comment]
fixed
