### ISSUE TITLE
Change icon theme?

### ISSUE THREAD

**Issue by maxigaz** [PapirusDevelopmentTeam/arc-kde#8]
I've noticed that in [this image](https://github.com/PapirusDevelopmentTeam/arc-kde/blob/master/extra/firefox/fix-toolbar.png), a custom icon theme is used instead of the one that comes with Firefox.

I'd like to know if it's possible to do this in the latest stable version of FF (V50.1.0).

**Comment by varlesh** [comment]
It's old screen. i'm not support Firefox Arc theme. It's  recommends for replace menubar color only
