### ISSUE TITLE
Blue solid border-bottom active window title

### ISSUE THREAD

**Issue by francoism90** [PapirusDevelopmentTeam/arc-kde#80]
This only happens when I select the Arc KDE color scheme.
Is this a bug? When I select Breeze the border is gone.

Thanks for the help. :)

Note: I'm using the latest arc-kde-git on Arch.

EDIT: Ah nvm. this seems to be new in Plasma 5.12. Is it possible to remove this border?

**Comment by varlesh** [comment]
> Blue solid border-bottom

What you mean? Screenshot please

**Comment by francoism90** [comment]
@varlesh https://i.imgur.com/p7YQCjh.png

**Comment by varlesh** [comment]
i'm not support breeze decoration. use aurorae or change colors for your self

**Comment by francoism90** [comment]
@varlesh OK, can you give a reason why? :)
It seems to work fine, and this isn't a arc-kde issue.

I have tried Kvantum but the buttons are way too small.

**Comment by varlesh** [comment]
Because Breeze it's another style and decoration.
On this repository only kvantum and aurorae.
