### ISSUE TITLE
Borders became bigger after update

### ISSUE THREAD

**Issue by Vavooon** [PapirusDevelopmentTeam/arc-kde#81]
After one of updates (2 to 3 weeks ago) I noticed that window borders became bigger.

Here is how they looked before update (pay attention to absent borders from left, right and bottom, there is just window content) ![](https://cn.pling.com/img/1/0/b/9/e5b48619353c483a54846674e0d5dc2e3833.png)

And here is look after update
![screenshot_20180214_115022](https://user-images.githubusercontent.com/1628401/36200525-4a48c6f6-117d-11e8-9dd2-bd5935e63b72.png)

**Comment by varlesh** [comment]
Not confirm this:
![image](https://user-images.githubusercontent.com/8083855/36207130-4811e53a-11ae-11e8-8111-eeec1a8cc4a9.png)
Try remove cache and relogin on plasma session:
`rm -rf ~/.cache/plasm*`

**Comment by Vavooon** [comment]
Thank you so much, it solved th issue.
