### ISSUE TITLE
checkbox gone after last update - firefox

### ISSUE THREAD

**Issue by idnovic** [PapirusDevelopmentTeam/arc-kde#82]
the dark version messes with firefox checkboxes

Install firefox 58 - install keybase extension - go to  about:addons - choose preferences on keybase - try to mark the checkboxes.

picture of how it looks under adwaita [screenshot](https://imagebin.ca/v/3t6jX6GPkm8r)
under arc-dark the checkboxes are gone

**Comment by varlesh** [comment]
I'm not developer GTK Theme. This repo for only Qt/KDE apps

**Comment by varlesh** [comment]
Firefox theme not development anymore and GTK too:
https://github.com/horst3180/arc-firefox-theme/commits/master
https://github.com/horst3180/arc-theme/commits/master
Available fork (but i'm not test it):
https://github.com/NicoHood/arc-theme

**Comment by idnovic** [comment]
I will look into it.

The newest update of your theme broke it thoo.
It used to work with the last version from last year.

**Comment by varlesh** [comment]
> The newest update of your theme broke it thoo.
It used to work with the last version from last year.

It's impossible, my customization does not affect  any GTK applications.
