### ISSUE TITLE
Arc-darker color scheme?

### ISSUE THREAD

**Issue by hxss** [PapirusDevelopmentTeam/arc-kde#86]
Hello. I'm new in KDE world. I was instal all settings like in description under main image in README.md:
`Engine: Kavntum | Kvantum Theme: Arc Darker | Aurorae decoration: Arc Dark | Plasma Theme: Arc Dark | Icons: Papirus`
But I have bugs in some native KDE apps. Main problem with "System settings":
![screenshot from 2018-05-03 01-07-02](https://user-images.githubusercontent.com/17298149/39546794-09032ac2-4e6f-11e8-8d17-1fb938645895.png)

I was try all methods for install your theme in my Arch linux:
```
package:arc-kde
aur:arc-kde-git
script:https://raw.githubusercontent.com/PapirusDevelopmentTeam/arc-kde/master/install-arc-kde-home.sh
```

I just don't have Arc-darker color scheme in "System settings". 
What I need to do to solve this bug?

**Comment by varlesh** [comment]
Kvantum not use system colors. This colors schemes for fix some bugs on KDE. Use Arc.
Also ArcDarker - it's Arc theme with dark toolbar. But it's impossible re-create on Breeze engine

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/39558056-d2236ad4-4e9c-11e8-91df-c40e7059e6bb.png)

**Comment by hxss** [comment]
@varlesh Hmm..it works. Thanks.
My fault that before this moment I was use Arc Color desktop theme and every time I activate Arc color scheme my panel transforms into white. So I thought, that this events are related.
