### ISSUE TITLE
login (SDDM) theme missing

### ISSUE THREAD

**Issue by lunemec** [PapirusDevelopmentTeam/arc-kde#90]
I remember having arc-kde themed login screen in my SDDM, but it dissapeared after some update. I still have themed lock screen, but I'm unable to find login screen with this theme.

Am I mistaken remembering having it?

**Comment by ArchangeGabriel** [comment]
I think so, never seen one. And at the very least not from here.

**Comment by lunemec** [comment]
Hmm, so I think it was the default "Breeze" just with correct wallpaper - the same as splash-screen + desktop. Thanks!
