### ISSUE TITLE
Rounded corners not working

### ISSUE THREAD

**Issue by weidler** [PapirusDevelopmentTeam/arc-kde#91]
I am having issues with the displaying of the rounded borders. Where there should be a rounded window corner, there is, but below is a sharp corner in black, as can be seen here:

![corner](https://user-images.githubusercontent.com/11197008/41190143-cac72da2-6bd9-11e8-815e-b039654ea704.png)

I did some googling and found out that it might be caused by issues with Aurorae. Is there a way to fix/workaround this issue? (I guess so since i saw many working screenshots :) )

Distro: Debian 9 Stretch

**Comment by varlesh** [comment]
disable Blur on plasma settings effect

**Comment by varlesh** [comment]
https://bugs.kde.org/show_bug.cgi?id=395725
