### ISSUE TITLE
KDE Plasma 5.13 Network widget big icons

### ISSUE THREAD

**Issue by mambusskruj** [PapirusDevelopmentTeam/arc-kde#92]
Hello PapirusDevelopmentTeam,
After today's KDE Plasma upgrade to version 5.13 (KDE Neon User Edition) I've notice that icons in Network widget are too large.

![image](https://user-images.githubusercontent.com/15351892/41354730-5e6eb57e-6f28-11e8-99fb-4a3d9bf15cc0.png)

**Comment by francoism90** [comment]
This also happens in v5.12.

**Comment by varlesh** [comment]
fixed:
```
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/arc-kde/master/install-arc-kde-root.sh | sh
rm -rf ~/.cache/plasm* ~/cache/ico*
killall -9 plasmashell
```
**ALT+F2** > `plasmashell`

**Comment by varlesh** [comment]
@mambusskruj @francoism90 Please check it...

**Comment by francoism90** [comment]
@varlesh This indeed fixed the issue, thanks. :)
I have submitted a bug report for Arch, since I'm using a package.

**Comment by mambusskruj** [comment]
seems like the bug still here
![image](https://user-images.githubusercontent.com/15351892/41404467-f99e6650-6fcf-11e8-84dd-b6e52531c780.png)

**Comment by varlesh** [comment]
@francoism90 thx
@mambusskruj Mybe plasma theme installed on home directory too? Change first comand and clear cache with plasma kill:
```
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/arc-kde/master/install-arc-kde-home.sh | sh
rm -rf ~/.cache/plasm* ~/cache/ico*
killall -9 plasmashell
```

**Comment by varlesh** [comment]
@mambusskruj Я имею ввиду тема дублируется в рутовой директории и хомяке, а потому юзается из хомяка предпочтительней. Вверху команда для обновления рутовой темы, чуть ниже для хомяка. Естественно, нужно удалить кеш, грохнуть плазму и перезапустить

**Comment by francoism90** [comment]
@varlesh You have a typo in the `rm` command, should be:
`rm -rf ~/.cache/plasm* ~/.cache/ico*`

Don't know if this was the fix for me, but I'm happy it works fine now. :)

**Comment by varlesh** [comment]
@mambusskruj  По скриншоту видно, что юзаются старые значки для wifi.
Сейчас вот такие:
![image](https://user-images.githubusercontent.com/8083855/41409351-ed548b1a-6fe6-11e8-83b2-d5ed278ac941.png)
Тут либо кеш не удалился, либо тема дублируется в ~/.local/share/ и /usr/share

**Comment by varlesh** [comment]
@francoism90 yes, thx:
`rm -rf ~/.cache/plasm* ~/.cache/ico*`

**Comment by varlesh** [comment]
My fault guys, sorry :)

**Comment by varlesh** [comment]
@francoism90 Don't report now on arch packagers... i'm soon relese new version.

**Comment by mambusskruj** [comment]
@varlesh точно. Однажды я ставил прямо из Look And Feel (но что-то с ней было не так, не помню уже), а во творой раз вот так:
```
sudo add-apt-repository ppa:papirus/papirus
sudo apt-get update
sudo apt-get install --install-recommends arc-kde
```

скажи, если устанавливать из ppa, куда оно заливается, в хомяк или в рут?

**Comment by SmartFinn** [comment]
@mambusskruj в root конечно.

**Comment by mambusskruj** [comment]
Удалил из хомдира тему, перезапустил плазму, всё ок. Спасибо, ребят!

**Comment by varlesh** [comment]
https://bugs.kde.org/show_bug.cgi?id=394580
