### ISSUE TITLE
Network Manager icons appear too large after update to fix it.

### ISSUE THREAD

**Issue by tjquillan** [PapirusDevelopmentTeam/arc-kde#93]
I am running Arch Linux and installed this through the package manager. In the network manager the icons all appear to large. Upon switching themes, toggling WiFi off and on again, and switching back to arc-kde this is fixed.

**Comment by varlesh** [comment]
remove cache and restart plasmashell:
https://github.com/PapirusDevelopmentTeam/arc-kde/issues/92

**Comment by varlesh** [comment]
https://bugs.kde.org/show_bug.cgi?id=394580
