### ISSUE TITLE
An alternative for Firefox-theme's

### ISSUE THREAD

**Issue by francoism90** [PapirusDevelopmentTeam/arc-kde#98]
Just a simple tweak I have discovered recently to match the colors of arc-kde (Dark) in FF: [Firefox Color](https://color.firefox.com/?theme=XQAAAAL-AAAAAAAAAABBqYhm849SCiazH1KEGccwS-xNVAWBvB94sLB6_ObzDAu7F4lSaIRlSbSraTJLt6uazOPk5Ssv_yEMJe8voQLhu_sE7w_68Y3uirJPkIV_AU6G38hAFLQG9mAxKqiXQ62m2OVx4HEk9Wt8VxHm9TI1GSCcNE9Grt9HepSXXfgCPrqJiswptaOYgcWS7pvH4jHurx4IkHiKbfDt-VZCZyGVIuWqq5PGJf7keUA)

Sorry this is not an question, although I do hope this is useful for some users.

**Comment by varlesh** [comment]
Thx for your suggestion, i think this better added info to upstream GTK theme:
https://github.com/nicohood/arc-theme
We customize only Qt-apps...

**Comment by francoism90** [comment]
@varlesh Oops! Thanks for pointing me to upstream. :)
